const canvas=document.getElementById('editorCanvas');
const ctx=canvas.getContext('2d');
const W=720,H=404;
const templates=[
 {id:1,name:'ONE TAKE',file:'assets/templates/template-01.png',show:'ONE TAKE CAM',title:'하츠투하츠',sub:'Hearts2Hearts',group:'Hearts2Hearts',color:'#e9f2ff',style:'onetake'},
 {id:2,name:'MBC KPOP',file:'assets/templates/template-02.png',show:'MBC KPOP',title:'카르멘',sub:'15-LOVE',group:'Hearts2Hearts',color:'#27b7ed',style:'mbc'},
 {id:3,name:'MUSIC CORE',file:'assets/templates/template-03.png',show:'SHOW! MUSIC CORE',title:'15-LOVE',sub:'HEARTS2HEARTS · EP61',group:'Hearts2Hearts',color:'#e850d4',style:'core'},
 {id:4,name:'ZOOM',file:'assets/templates/template-04.png',show:'FACE CAM',title:'지우',sub:'Hearts2Hearts',group:'Hearts2Hearts',color:'#4bc4f4',style:'zoom'},
 {id:5,name:'MBC FULLCAM',file:'assets/templates/template-05.png',show:'MBC KPOP',title:'15-LOVE',sub:'Hearts2Hearts',group:'Hearts2Hearts',color:'#70bff2',style:'full'},
 {id:6,name:'MUBEAT',file:'assets/templates/template-06.png',show:'MUSIC BANK',title:'15-LOVE',sub:'Hearts2Hearts',group:'Hearts2Hearts',color:'#f04ac7',style:'mubeat'},
 {id:7,name:'MUSIC BANK',file:'assets/templates/template-07.png',show:'MUSIC BANK',title:'15-LOVE',sub:'Hearts2Hearts',group:'Hearts2Hearts',color:'#f04ac7',style:'bank'},
 {id:8,name:'FT SONG',file:'assets/templates/template-08.png',show:'FT SONG',title:'Hearts2Hearts',sub:'FT Songs n°699',group:'Hearts2Hearts',color:'#c9e4ef',style:'collage'},
 {id:9,name:'MNET',file:'assets/templates/template-09.png',show:'MPD 직캠',title:'15-LOVE',sub:'Hearts2Hearts',group:'Hearts2Hearts',color:'#ef3d98',style:'mnet'},
 {id:10,name:'SHOW CHAMPION',file:'assets/templates/template-10.png',show:'SHOW CHAMPION',title:'15-LOVE',sub:'Hearts2Hearts',group:'Hearts2Hearts',color:'#ff72a0',style:'champ'}
];
let state={template:templates[1],color:templates[1].color,photo:null,photoMode:'fill',zoom:1,selected:'title',texts:{show:'MBC KPOP',group:'Hearts2Hearts',title:'15-LOVE',sub:'Hearts2Hearts'},positions:{show:{x:40,y:43},group:{x:40,y:86},title:{x:40,y:132},sub:{x:40,y:378}}};
const photo=new Image();
const templateImages={};
let drag=null;
function hexToRgb(hex){hex=hex.replace('#','');return {r:parseInt(hex.slice(0,2),16),g:parseInt(hex.slice(2,4),16),b:parseInt(hex.slice(4,6),16)}}
function rgba(hex,a){const c=hexToRgb(hex);return `rgba(${c.r},${c.g},${c.b},${a})`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderTemplates(){const grid=document.getElementById('templateGrid');grid.innerHTML=templates.map(t=>`<button class="template-card ${t.id===state.template.id?'active':''}" data-id="${t.id}" title="${t.name}"><img src="${t.file}" alt="${esc(t.name)}"><span class="check">✓</span></button>`).join('');grid.querySelectorAll('.template-card').forEach(b=>b.onclick=()=>selectTemplate(+b.dataset.id));templates.forEach(t=>{const im=new Image();im.src=t.file;templateImages[t.id]=im;});}
function selectTemplate(id){const t=templates.find(x=>x.id===id);state.template=t;state.color=t.color;state.texts={show:t.show,group:t.group,title:t.title,sub:t.sub};state.positions={show:{x:40,y:43},group:{x:40,y:86},title:{x:40,y:132},sub:{x:40,y:378}};document.getElementById('showInput').value=t.show;document.getElementById('groupInput').value=t.group;document.getElementById('titleInput').value=t.title;document.getElementById('subInput').value=t.sub;document.getElementById('colorInput').value=t.color;document.querySelectorAll('.swatch').forEach(s=>s.classList.toggle('active',s.dataset.color===t.color));renderTemplates();draw();toast('テンプレートを変更しました');}
function fitImage(im,mode){const r=im.width/im.height;const cr=W/H;let dw,dh;if(mode==='fit'){dw=r>cr?W:W*(r/cr);dh=r>cr?H* (r/cr):H}else{dw=r>cr?W:W*(r/cr);dh=r>cr?H*(r/cr):H; if(mode==='fill' && r>cr){dw=H*r;dh=H}else if(mode==='fill'){dw=W;dh=W/r}}return {dw,dh,x:(W-dw)/2,y:(H-dh)/2}}
function drawPhoto(){if(!state.photo)return false;const box=fitImage(photo,state.photoMode);ctx.save();ctx.filter=state.template.style==='mubeat'||state.template.style==='bank'?'saturate(1.1) contrast(1.03)':'saturate(1.04)';ctx.drawImage(photo,box.x,box.y,box.dw,box.dh);ctx.restore();return true}
function gradientBg(){const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#dff3fb');g.addColorStop(.55,state.color);g.addColorStop(1,'#ffb5dd');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawStyle(){const t=state.template.style; if(!state.photo){gradientBg();} else {if(t==='core'||t==='mubeat'||t==='bank'||t==='champ')ctx.fillStyle=rgba(state.color,.14),ctx.fillRect(0,0,W,H);}
 ctx.save();
 if(t==='mbc'){ctx.fillStyle=rgba('#ffffff',.84);ctx.fillRect(0,0,330,H);ctx.fillStyle=rgba(state.color,.9);ctx.fillRect(0,0,12,H);ctx.fillStyle='#fff';ctx.fillRect(25,24,115,34);ctx.fillStyle=state.color;ctx.font='700 20px Inter';ctx.fillText('MBC KPOP',40,47)}
 if(t==='onetake'){ctx.fillStyle='#ffffff';ctx.fillRect(0,H-92,W,92);ctx.strokeStyle=state.color;ctx.lineWidth=3;ctx.strokeRect(18,18,W-36,H-36);}
 if(t==='core'){ctx.fillStyle=rgba(state.color,.9);ctx.fillRect(0,0,240,88);ctx.beginPath();ctx.arc(720,0,205,0,Math.PI/2);ctx.fillStyle=rgba(state.color,.62);ctx.fill();ctx.fillStyle='#fff';ctx.font='800 27px Inter';ctx.fillText('SHOW',28,37);ctx.fillText('MUSIC',28,66);ctx.fillStyle=rgba('#fff',.25);for(let x=250;x<720;x+=18)for(let y=0;y<404;y+=18){ctx.beginPath();ctx.arc(x,y,1,0,Math.PI*2);ctx.fill()}}
 if(t==='zoom'){ctx.fillStyle=rgba('#fff',.15);ctx.fillRect(0,0,W,H);ctx.strokeStyle=rgba('#fff',.8);ctx.lineWidth=3;ctx.strokeRect(8,8,W-16,H-16)}
 if(t==='full'){ctx.fillStyle=rgba(state.color,.2);ctx.fillRect(0,0,W,H);ctx.strokeStyle='#fff';ctx.lineWidth=6;ctx.strokeRect(7,7,W-14,H-14);for(let x=14;x<W;x+=22){ctx.fillStyle=rgba('#fff',.28);ctx.beginPath();ctx.arc(x,14,2,0,7);ctx.fill()}}
 if(t==='mubeat'||t==='bank'){ctx.strokeStyle=state.color;ctx.lineWidth=3;ctx.strokeRect(15,15,W-30,H-30);ctx.fillStyle=rgba(state.color,.9);ctx.fillRect(0,0,W,13);ctx.fillRect(0,H-13,W,13)}
 if(t==='collage'){ctx.fillStyle='#d5eff7';ctx.fillRect(W/2-18,0,36,H);ctx.fillStyle=rgba('#fff',.88);ctx.fillRect(0,0,W,22);}
 if(t==='mnet'){ctx.fillStyle=rgba(state.color,.9);ctx.fillRect(0,0,W,14);ctx.fillRect(0,H-14,W,14);ctx.fillStyle='#fff';ctx.font='800 16px Inter';ctx.fillText('MPD 직캠',26,45)}
 if(t==='champ'){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(9,9,W-18,H-18);ctx.fillStyle=rgba(state.color,.78);ctx.fillRect(0,0,W,12);ctx.fillRect(0,H-12,W,12);}
 ctx.restore();}
function drawText(key){const p=state.positions[key];const text=state.texts[key]||'';ctx.save();ctx.shadowColor='rgba(0,0,0,.35)';ctx.shadowBlur=key==='title'?7:4;ctx.shadowOffsetY=2;let size=key==='title'?48:key==='group'?27:key==='show'?16:17;let weight=key==='title'?800:700;ctx.font=`${weight} ${size}px Inter,"Noto Sans JP",sans-serif`;ctx.textBaseline='alphabetic';let color='#fff';if(state.template.style==='mbc'&&key==='title')color='#fff';if(state.template.style==='onetake'&&key==='title')color='#fff';if(state.template.style==='collage')color='#fff';ctx.fillStyle=color;let max=660;while(ctx.measureText(text).width>max&&size>10){size--;ctx.font=`${weight} ${size}px Inter,"Noto Sans JP",sans-serif`}ctx.fillText(text,p.x,p.y);if(state.selected===key){const m=ctx.measureText(text);ctx.shadowBlur=0;ctx.strokeStyle=rgba(state.color,.9);ctx.lineWidth=1.5;ctx.setLineDash([5,4]);ctx.strokeRect(p.x-7,p.y-size-6,m.width+14,size+13);ctx.setLineDash([])}ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);drawPhoto();drawStyle();['show','group','title','sub'].forEach(drawText);}
function bindInputs(){[['show','showInput'],['group','groupInput'],['title','titleInput'],['sub','subInput']].forEach(([key,id])=>{document.getElementById(id).addEventListener('input',e=>{state.texts[key]=e.target.value;state.selected=key;draw();updateLayers();});});}
function updateLayers(){const list=document.getElementById('layerList');const labels={show:'番組名',group:'グループ名',title:'メインタイトル',sub:'サブタイトル'};list.innerHTML=Object.keys(labels).map(k=>`<div class="layer-item ${state.selected===k?'active':''}" data-layer="${k}"><span>${labels[k]}</span><button>↕</button></div>`).join('');list.querySelectorAll('.layer-item').forEach(x=>x.onclick=()=>{state.selected=x.dataset.layer;draw();updateLayers()});}
function setupDrag(){canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;let hit=null;for(const key of ['sub','title','group','show']){const p=state.positions[key];const text=state.texts[key]||'';let size=key==='title'?48:key==='group'?27:key==='show'?16:17;ctx.font=`700 ${size}px Inter,"Noto Sans JP",sans-serif`;const w=ctx.measureText(text).width;if(x>=p.x-15&&x<=p.x+w+15&&y>=p.y-size-15&&y<=p.y+15){hit=key;break}}if(hit){state.selected=hit;drag={key,ox:x-state.positions[hit].x,oy:y-state.positions[hit].y};canvas.setPointerCapture(e.pointerId);updateLayers();draw()}});canvas.addEventListener('pointermove',e=>{if(!drag)return;const r=canvas.getBoundingClientRect();const x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;state.positions[drag.key]={x:Math.max(4,Math.min(W-20,x-drag.ox)),y:Math.max(18,Math.min(H-5,y-drag.oy))};draw()});canvas.addEventListener('pointerup',()=>drag=null);}
function handlePhoto(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{photo.onload=()=>{state.photo=reader.result;state.photoMode='fill';draw();toast('写真を読み込みました')};photo.src=reader.result};reader.readAsDataURL(file)}
function setupPhoto(){const input=document.getElementById('photoInput'),drop=document.getElementById('dropzone');input.onchange=e=>handlePhoto(e.target.files[0]);['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragover')}));drop.addEventListener('drop',e=>handlePhoto(e.dataTransfer.files[0]));document.getElementById('fitPhoto').onclick=()=>{state.photoMode='fit';draw()};document.getElementById('fillPhoto').onclick=()=>{state.photoMode='fill';draw()}}
function setupColors(){document.querySelectorAll('.swatch').forEach(s=>s.onclick=()=>{state.color=s.dataset.color;document.getElementById('colorInput').value=state.color;document.querySelectorAll('.swatch').forEach(x=>x.classList.toggle('active',x===s));draw()});document.getElementById('colorInput').oninput=e=>{state.color=e.target.value;document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));draw()}}
function download(){draw();const url=canvas.toDataURL('image/png');const a=document.createElement('a');a.href=url;a.download=`thumbly-${Date.now()}.png`;a.click();saveHistory(url);toast('PNGを書き出しました。作成履歴にも保存しました');}
function saveHistory(image){const key='thumbly-history-v1';let list=[];try{list=JSON.parse(localStorage.getItem(key)||'[]')}catch{};list.unshift({id:Date.now(),image,template:state.template.name,title:state.texts.title,group:state.texts.group,date:new Date().toLocaleString('ja-JP')});list=list.slice(0,12);try{localStorage.setItem(key,JSON.stringify(list))}catch{list=list.slice(0,5);localStorage.setItem(key,JSON.stringify(list))}renderHistory()}
function getHistory(){try{return JSON.parse(localStorage.getItem('thumbly-history-v1')||'[]')}catch{return[]}}
function renderHistory(){const list=getHistory(),grid=document.getElementById('historyGrid'),empty=document.getElementById('emptyHistory');grid.innerHTML=list.map(x=>`<article class="history-card"><img src="${x.image}" alt="${esc(x.title)}"><div class="history-meta"><strong>${esc(x.group)} · ${esc(x.title)}</strong><span>${esc(x.template)} / ${esc(x.date)}</span><div class="history-actions"><button class="use" data-use="${x.id}">この作品を表示</button><button data-del="${x.id}">削除</button></div></div></article>`).join('');empty.style.display=list.length?'none':'block';grid.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const x=list.find(y=>y.id==b.dataset.use);if(x){const im=new Image();im.onload=()=>{ctx.clearRect(0,0,W,H);ctx.drawImage(im,0,0,W,H);document.querySelector('[data-view="editor"]').click();toast('履歴の作品を表示しました（再編集用の画像として読み込み）')};im.src=x.image}});grid.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const a=list.filter(x=>x.id!=b.dataset.del);localStorage.setItem('thumbly-history-v1',JSON.stringify(a));renderHistory()})}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function setupNav(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();const v=b.dataset.view;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));document.getElementById(v==='editor'?'editorView':'historyView').classList.add('active-view');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='history')renderHistory()}))}
document.getElementById('downloadBtn').onclick=download;document.getElementById('resetBtn').onclick=()=>{selectTemplate(2);state.photo=null;draw();toast('初期状態に戻しました')};document.getElementById('clearHistoryBtn').onclick=()=>{if(confirm('作成履歴をすべて削除しますか？')){localStorage.removeItem('thumbly-history-v1');renderHistory();toast('履歴を削除しました')}};let zoom=1;document.getElementById('zoomIn').onclick=()=>{zoom=Math.min(1.5,zoom+.1);document.getElementById('canvasWrap').style.transform=`scale(${zoom})`;document.getElementById('zoomLabel').textContent=Math.round(zoom*100)+'%'};document.getElementById('zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.1);document.getElementById('canvasWrap').style.transform=`scale(${zoom})`;document.getElementById('zoomLabel').textContent=Math.round(zoom*100)+'%'};
renderTemplates();bindInputs();setupPhoto();setupColors();setupDrag();setupNav();updateLayers();draw();renderHistory();
