const $=id=>document.getElementById(id), C=$('canvas'),ctx=C.getContext('2d'),W=720,H=404;
const FONT_LIST=[
 ['Noto Sans KR','韓国語 / 標準'],['Black Han Sans','韓国語 / 極太'],['Do Hyeon','韓国語 / 番組系'],['Jua','韓国語 / 丸ゴ'],['Gowun Dodum','韓国語 / やわらか'],['Nanum Gothic','韓国語 / ゴシック'],['Nanum Myeongjo','韓国語 / 明朝'],['IBM Plex Sans KR','韓国語 / UI'],['Noto Serif KR','韓国語 / 明朝'],['Inter','英数字 / UI'],['Montserrat','英数字 / 幾何学'],['Poppins','英数字 / 丸み'],['Outfit','英数字 / モダン'],['DM Sans','英数字 / クリーン'],['Roboto','英数字 / 定番'],['Roboto Condensed','英数字 / 縦長'],['Oswald','英数字 / 縦長強調'],['Barlow Condensed','英数字 / スポーツ'],['Bebas Neue','英数字 / 極太タイトル'],['Anton','英数字 / 極太'],['Archivo Black','英数字 / 強太'],['League Spartan','英数字 / 強太'],['Titillium Web','英数字 / テック'],['Ubuntu','英数字 / フレンドリー'],['Space Grotesk','英数字 / デザイン'],['Space Mono','英数字 / モノ'],['Noto Sans JP','日本語 / ゴシック'],['Noto Serif JP','日本語 / 明朝'],['Archivo','英数字 / 放送系'],['Playfair Display','英数字 / セリフ']
];
$('font').innerHTML='<option value="auto">テンプレート準拠</option>'+FONT_LIST.map(x=>`<option value="${x[0]}">${x[0]} — ${x[1]}</option>`).join('');
const T=[
{id:1,n:'ONE TAKE CAM',f:'template-01.png',c:'#dcecff',font:'Noto Sans KR',fonts:{show:16,group:28,title:47,sub:18},pos:{show:[25,264],group:[22,341],title:[22,311],sub:[24,382]},text:{show:'ONE TAKE CAM',group:'Hearts2Hearts',title:'하츠투하츠',sub:'Hearts2Hearts'}},
{id:2,n:'MBC KPOP',f:'template-02.png',c:'#2ab7ed',font:'Black Han Sans',fonts:{show:19,group:32,title:48,sub:25},pos:{show:[39,47],group:[39,138],title:[39,186],sub:[40,247]},text:{show:'MBC KPOP',group:'Hearts2Hearts',title:'카르멘',sub:'15-LOVE'}},
{id:3,n:'SHOW! MUSIC CORE',f:'template-03.png',c:'#e64bd2',font:'Noto Sans KR',fonts:{show:27,group:27,title:48,sub:22},pos:{show:[25,57],group:[17,315],title:[17,352],sub:[18,292]},text:{show:'SHOW MUSIC CORE',group:'HEARTS2HEARTS · EP61',title:'15-LOVE',sub:''}},
{id:4,n:'ZOOM FACE CAM',f:'template-04.png',c:'#4dbef0',font:'Noto Sans KR',fonts:{show:16,group:27,title:47,sub:20},pos:{show:[24,264],group:[24,341],title:[24,311],sub:[24,382]},text:{show:'FACE CAM',group:'Hearts2Hearts',title:'지우',sub:'Hearts2Hearts'}},
{id:5,n:'MBC FULLCAM',f:'template-05.png',c:'#68bdf1',font:'Noto Sans KR',fonts:{show:16,group:27,title:49,sub:21},pos:{show:[38,45],group:[38,342],title:[38,302],sub:[38,371]},text:{show:'MBC KPOP',group:'Hearts2Hearts',title:'15-LOVE',sub:'Show! Music Core Fullcam'}},
{id:6,n:'MUSIC BANK / 01',f:'template-06.png',c:'#f04bc6',font:'Montserrat',fonts:{show:16,group:33,title:46,sub:22},pos:{show:[25,45],group:[25,340],title:[25,305],sub:[25,370]},text:{show:'♪',group:'Hearts2Hearts',title:'15-LOVE',sub:''}},
{id:7,n:'MUSIC BANK / 02',f:'template-07.png',c:'#f04bc6',font:'Montserrat',fonts:{show:16,group:33,title:46,sub:22},pos:{show:[26,47],group:[25,340],title:[25,306],sub:[25,370]},text:{show:'MUSIC BANK',group:'Hearts2Hearts',title:'15-LOVE',sub:''}},
{id:8,n:'FT SONG',f:'template-08.png',c:'#bfe2ed',font:'Inter',fonts:{show:27,group:18,title:48,sub:18},pos:{show:[169,35],group:[167,383],title:[168,352],sub:[420,383]},text:{show:'Hearts2Hearts',group:'FT Songs n°699',title:'',sub:''}},
{id:9,n:'MNET / MPD',f:'template-09.png',c:'#ef3d98',font:'Noto Sans KR',fonts:{show:16,group:27,title:49,sub:22},pos:{show:[23,48],group:[24,382],title:[24,352],sub:[24,388]},text:{show:'MPD직캠',group:'Hearts2Hearts',title:'15-LOVE',sub:''}},
{id:10,n:'SHOW CHAMPION',f:'template-10.png',c:'#ff72a0',font:'Noto Sans KR',fonts:{show:17,group:29,title:47,sub:22},pos:{show:[25,320],group:[25,350],title:[25,305],sub:[25,383]},text:{show:'',group:'Hearts2Hearts',title:'15-LOVE',sub:''}}
];
const state={t:T[1],photo:null,photoMode:'fill',bg:'photo',theme:T[1].c,selected:null,grid:false,safe:false,zoom:1,shadow:true,stroke:false,glow:false,box:false,layers:['photo','show','group','title','sub'],texts:{},pos:{},style:{font:'auto',size:48,weight:700,opacity:100,text:'#fff',stroke:'#000',box:'#000',rotation:0,tracking:0,lineHeight:1,scaleX:1,scaleY:1},photoFx:{brightness:100,contrast:100,saturation:100,blur:0},history:[],future:[]};
const imgs={};T.forEach(t=>{const im=new Image();im.src='assets/templates/'+t.f;imgs[t.id]=im});const brands={};T.forEach(t=>{const im=new Image();im.src='assets/branding/branding-'+String(t.id).padStart(2,'0')+'.png';brands[t.id]=im});const photo=new Image();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function clone(){return JSON.parse(JSON.stringify({t:state.t.id,bg:state.bg,theme:state.theme,texts:state.texts,pos:state.pos,style:state.style,shadow:state.shadow,stroke:state.stroke,glow:state.glow,box:state.box,photoFx:state.photoFx}))}function push(){state.history.push(clone());if(state.history.length>60)state.history.shift();state.future=[]}function restore(o){state.t=T.find(t=>t.id===o.t)||T[1];state.bg=o.bg;state.theme=o.theme;state.texts=o.texts;state.pos=o.pos;state.style=o.style;state.shadow=o.shadow;state.stroke=o.stroke;state.glow=o.glow;state.box=o.box;state.photoFx=o.photoFx||state.photoFx;syncUI();draw()}function undo(){if(!state.history.length)return;state.future.push(clone());restore(state.history.pop())}function redo(){if(!state.future.length)return;state.history.push(clone());restore(state.future.pop())}
function fit(im,mode){const r=im.width/im.height,cr=W/H;let dw,dh;if(mode==='fit'){if(r>cr){dw=W;dh=W/r}else{dh=H;dw=H*r}}else{if(r>cr){dh=H;dw=H*r}else{dw=W;dh=W/r}}return{dw,dh,x:(W-dw)/2,y:(H-dh)/2}}
function basePhoto(){if(!state.photo)return;const b=fit(photo,state.photoMode);ctx.save();const f=state.photoFx;ctx.filter=`brightness(${f.brightness}%) contrast(${f.contrast}%) saturate(${f.saturation}%) blur(${f.blur}px)`;ctx.drawImage(photo,b.x,b.y,b.dw,b.dh);ctx.restore()}
function original(){const im=imgs[state.t.id];if(im.complete)ctx.drawImage(im,0,0,W,H)}
function rgb(h){h=h.replace('#','');return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]}function rgba(h,a){const[r,g,b]=rgb(h);return`rgba(${r},${g},${b},${a})`}
function decor(){const s=state.t.id,c=state.theme;ctx.save();if(s===2){ctx.fillStyle='rgba(255,255,255,.82)';ctx.fillRect(0,0,330,H);ctx.fillStyle=rgba(c,.9);ctx.fillRect(0,0,11,H)}if(s===3){ctx.fillStyle=rgba(c,.9);ctx.fillRect(0,0,240,88);ctx.beginPath();ctx.arc(720,0,205,0,Math.PI/2);ctx.fillStyle=rgba(c,.62);ctx.fill()}if(s===8){ctx.fillStyle='#d5eff7';ctx.fillRect(W/2-18,0,36,H)}if(s===9){ctx.fillStyle=rgba(c,.9);ctx.fillRect(0,0,W,13);ctx.fillRect(0,H-13,W,13)}ctx.restore();const b=brands[state.t.id];if(b&&b.complete)ctx.drawImage(b,0,0,W,H)}
function fontFor(k){return state.style.font==='auto'?(state.t.font==='auto'?'Noto Sans KR':state.t.font):state.style.font}
function textMetrics(k){const size=k===state.selected?state.style.size:(state.t.fonts[k]||20);const f=fontFor(k),w=k===state.selected?state.style.weight:700;ctx.font=`${w} ${size}px "${f}"`;const tx=state.texts[k]||'';return{font:f,size,weight:w,w:ctx.measureText(tx).width}}
function drawText(k){const tx=state.texts[k]||'';if(!tx)return;const p=state.pos[k]||[20,40],m=textMetrics(k),st=state.style;ctx.save();ctx.globalAlpha=st.opacity/100;ctx.font=`${m.weight} ${m.size}px "${m.font}"`;ctx.textBaseline='alphabetic';ctx.translate(p[0],p[1]);ctx.rotate((st.rotation||0)*Math.PI/180);ctx.scale(st.scaleX||1,st.scaleY||1);if(st.tracking){ctx.letterSpacing=st.tracking+'px'}if(state.box&&state.selected===k){ctx.fillStyle=rgba(st.box,.72);ctx.fillRect(-8,-m.size-8,m.w+16,m.size+16)}if(state.glow&&state.selected===k){ctx.shadowColor=rgba(state.theme,.9);ctx.shadowBlur=16}else if(state.shadow){ctx.shadowColor='rgba(0,0,0,.5)';ctx.shadowBlur=k==='title'?7:4;ctx.shadowOffsetY=2}if(state.stroke){ctx.lineWidth=Math.max(2,m.size*.045);ctx.strokeStyle=st.stroke;ctx.strokeText(tx,0,0)}ctx.fillStyle=st.text;ctx.fillText(tx,0,0);if(state.selected===k){ctx.shadowBlur=0;ctx.setLineDash([5,4]);ctx.strokeStyle=rgba(state.theme,.95);ctx.lineWidth=1;ctx.strokeRect(-7,-m.size-7,m.w+14,m.size+14);ctx.setLineDash([])}ctx.restore()}
function guides(){if(state.grid){ctx.save();ctx.strokeStyle='rgba(114,119,255,.16)';ctx.lineWidth=1;for(let x=0;x<=W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<=H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.restore()}if(state.safe){ctx.save();ctx.strokeStyle='rgba(255,70,110,.6)';ctx.setLineDash([6,5]);ctx.strokeRect(36,24,W-72,H-48);ctx.restore()}}
function draw(){ctx.clearRect(0,0,W,H);state.bg==='original'?original():basePhoto();if(state.bg!=='original'){decor();state.layers.filter(x=>x!=='photo'&&!x.startsWith('shape:')).forEach(drawText);drawShapes()}else if(state.selected&&state.texts[state.selected]){}guides()}
const shapes=[];function drawShapes(){shapes.forEach(s=>{ctx.save();ctx.globalAlpha=s.opacity;ctx.fillStyle=s.color;ctx.strokeStyle=s.color;if(s.type==='rect')ctx.fillRect(s.x,s.y,s.w,s.h);if(s.type==='circle'){ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}if(s.type==='line'){ctx.lineWidth=s.width;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x2,s.y2);ctx.stroke()}ctx.restore()})}
function renderTemplates(){$('templates').innerHTML=T.map(t=>`<button class="template ${t.id===state.t.id?'active':''}" data-id="${t.id}"><img src="assets/templates/${t.f}"><span>${esc(t.n)}</span><i class="mark">✓</i></button>`).join('');document.querySelectorAll('.template').forEach(b=>b.onclick=()=>selectTemplate(+b.dataset.id))}
function selectTemplate(id){push();state.t=T.find(t=>t.id===id)||T[1];state.bg='photo';state.theme=state.t.c;state.texts={...state.t.text};state.pos=JSON.parse(JSON.stringify(state.t.pos));state.selected=null;state.style={...state.style,font:'auto',size:state.t.fonts.title,weight:700,opacity:100,text:'#fff',stroke:'#000',box:'#000',rotation:0,tracking:0,lineHeight:1,scaleX:1,scaleY:1};syncUI();draw();toast('テンプレートの位置・フォント・装飾を適用しました')}
function renderLayers(){const names={show:'番組名',group:'グループ名',title:'メインタイトル',sub:'サブタイトル'};$('layers').innerHTML=state.layers.filter(x=>x!=='photo'&&!x.startsWith('shape:')).map(k=>`<button class="layer ${k===state.selected?'active':''}" data-k="${k}"><b>${({show:'01',group:'02',title:'03',sub:'04'})[k]||'•'}</b>${esc(names[k]||k)}</button>`).join('');document.querySelectorAll('.layer').forEach(b=>b.onclick=()=>{state.selected=b.dataset.k;syncUI();draw()})}
function syncUI(){renderTemplates();renderLayers();['show','group','title','sub'].forEach(k=>$(k).value=state.texts[k]||'');$('templateName').textContent=state.t.n;$('theme').value=state.theme;$('font').value=state.style.font;$('fontSize').value=state.style.size;$('fontSizeOut').value=Math.round(state.style.size);$('weight').value=state.style.weight;$('tracking').value=state.style.tracking;$('trackingOut').value=state.style.tracking;$('lineHeight').value=state.style.lineHeight;$('lineHeightOut').value=Number(state.style.lineHeight).toFixed(2);$('rotation').value=state.style.rotation;$('rotationOut').value=state.style.rotation+'°';$('opacity').value=state.style.opacity;$('opacityOut').value=state.style.opacity+'%';$('scaleX').value=state.style.scaleX;$('scaleXOut').value=Number(state.style.scaleX).toFixed(2);$('scaleY').value=state.style.scaleY;$('scaleYOut').value=Number(state.style.scaleY).toFixed(2);$('textColor').value=state.style.text;$('strokeColor').value=state.style.stroke;$('boxColor').value=state.style.box;$('shadow').classList.toggle('active',state.shadow);$('stroke').classList.toggle('active',state.stroke);$('glow').classList.toggle('active',state.glow);$('box').classList.toggle('active',state.box);$('selectedLabel').textContent=state.selected?({show:'番組名',group:'グループ名',title:'メインタイトル',sub:'サブタイトル'}[state.selected]||'要素'):'未選択';$('fontPreview').style.fontFamily=`"${fontFor(state.selected||'title')}"`;$('fontPreview').textContent=state.selected?(state.texts[state.selected]||'プレビュー'):'Hearts2Hearts 15-LOVE';['brightness','contrast','saturation','blur'].forEach(k=>{$(k).value=state.photoFx[k];$(k+'Out').value=k==='blur'?state.photoFx[k]:state.photoFx[k]+'%'})}
function inputEvents(){['show','group','title','sub'].forEach(k=>$(k).onfocus=()=>{state.selected=k;syncUI()});['show','group','title','sub'].forEach(k=>$(k).oninput=()=>{state.texts[k]=$(k).value;state.selected=k;draw();renderLayers()});$('font').onchange=e=>{push();state.style.font=e.target.value;draw();syncUI()};$('fontSize').oninput=e=>{state.style.size=+e.target.value;$('fontSizeOut').value=Math.round(state.style.size);draw();syncUI()};$('weight').onchange=e=>{push();state.style.weight=+e.target.value;draw()};[['tracking','trackingOut',v=>v],['lineHeight','lineHeightOut',v=>Number(v).toFixed(2)],['rotation','rotationOut',v=>v+'°'],['opacity','opacityOut',v=>v+'%'],['scaleX','scaleXOut',v=>Number(v).toFixed(2)],['scaleY','scaleYOut',v=>Number(v).toFixed(2)]].forEach(([id,out,fmt])=>$(id).oninput=e=>{state.style[id==='tracking'?'tracking':id]=+e.target.value;$(out).value=fmt(e.target.value);draw()});[['brightness','brightnessOut'],['contrast','contrastOut'],['saturation','saturationOut'],['blur','blurOut']].forEach(([id,out])=>$(id).oninput=e=>{state.photoFx[id]=+e.target.value;$(out).value=id==='blur'?e.target.value:e.target.value+'%';draw()});$('textColor').oninput=e=>{state.style.text=e.target.value;draw()};$('strokeColor').oninput=e=>{state.style.stroke=e.target.value;draw()};$('boxColor').oninput=e=>{state.style.box=e.target.value;draw()};$('theme').oninput=e=>{state.theme=e.target.value;draw()};['shadow','stroke','glow','box'].forEach(id=>$(id).onclick=()=>{state[id]=!state[id];$(id).classList.toggle('active',state[id]);draw()});document.querySelectorAll('[data-design]').forEach(b=>b.onclick=()=>renderDesign(b.dataset.design))}
function renderDesign(type){document.querySelectorAll('[data-design]').forEach(b=>b.classList.toggle('active',b.dataset.design===type));const p=$('designPanel');if(type==='color')p.innerHTML=`<div class="design-actions"><button data-c="#6e73ff">Lavender</button><button data-c="#45c7e8">Aqua</button><button data-c="#ed5cc8">Pink</button><button data-c="#65c68a">Mint</button><button data-c="#ff8a9d">Coral</button><button data-c="#ffd166">Lemon</button></div>`;if(type==='shape')p.innerHTML=`<div class="design-actions"><button data-shape="rect">＋ 長方形</button><button data-shape="circle">＋ 円</button><button data-shape="line">＋ ライン</button><button data-shape="gradient">＋ グラデーション</button></div>`;if(type==='line')p.innerHTML=`<div class="design-actions"><button data-line="top">上ライン</button><button data-line="bottom">下ライン</button><button data-line="frame">フレーム</button><button data-line="dots">ドット枠</button></div>`;p.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.c;$('theme').value=state.theme;draw()});p.querySelectorAll('[data-shape]').forEach(b=>b.onclick=()=>addShape(b.dataset.shape));p.querySelectorAll('[data-line]').forEach(b=>b.onclick=()=>addLine(b.dataset.line))}
function addShape(type){push();if(type==='rect')shapes.push({type:'rect',x:30,y:30,w:180,h:55,color:rgba(state.theme,.75),opacity:1});if(type==='circle')shapes.push({type:'circle',x:620,y:65,r:42,color:rgba(state.theme,.75),opacity:1});if(type==='line')shapes.push({type:'line',x:40,y:200,x2:680,y2:200,width:3,color:state.theme,opacity:1});if(type==='gradient'){const g=ctx.createLinearGradient(0,0,W,0);g.addColorStop(0,state.theme);g.addColorStop(1,'transparent');shapes.push({type:'rect',x:0,y:0,w:W,h:H,color:g,opacity:.3})}draw()}
function addLine(type){push();if(type==='top')shapes.push({type:'line',x:0,y:10,x2:W,y2:10,width:3,color:state.theme,opacity:1});if(type==='bottom')shapes.push({type:'line',x:0,y:H-10,x2:W,y2:H-10,width:3,color:state.theme,opacity:1});if(type==='frame')shapes.push({type:'line',x:12,y:12,x2:W-12,y2:12,width:2,color:'#fff',opacity:1},{type:'line',x:12,y:H-12,x2:W-12,y2:H-12,width:2,color:'#fff',opacity:1});if(type==='dots'){for(let x=15;x<W;x+=20)shapes.push({type:'circle',x,y:12,r:2,color:'#fff',opacity:1},{type:'circle',x,y:H-12,r:2,color:'#fff',opacity:1})}draw()}
function handleFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{photo.onload=()=>{state.photo=r.result;state.bg='photo';draw();toast('写真を読み込みました')};photo.src=r.result};r.readAsDataURL(file)}
$('photo').onchange=e=>handleFile(e.target.files[0]);['dragenter','dragover'].forEach(ev=>$('drop').addEventListener(ev,e=>{e.preventDefault();$('drop').classList.add('drag')}));['dragleave','drop'].forEach(ev=>$('drop').addEventListener(ev,e=>{e.preventDefault();$('drop').classList.remove('drag')}));$('drop').addEventListener('drop',e=>handleFile(e.dataTransfer.files[0]));
function hit(x,y){for(const k of [...state.layers].reverse()){if(k==='photo'||!state.texts[k])continue;const p=state.pos[k],m=textMetrics(k);if(x>=p[0]-12&&x<=p[0]+m.w+12&&y>=p[1]-m.size-15&&y<=p[1]+15)return k}return null}
let drag=null;C.addEventListener('pointerdown',e=>{const r=C.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height,k=hit(x,y);if(k){state.selected=k;drag={k,dx:x-state.pos[k][0],dy:y-state.pos[k][1]};C.setPointerCapture(e.pointerId);syncUI();draw()}else{state.selected=null;syncUI();draw()}});C.addEventListener('pointermove',e=>{if(!drag)return;const r=C.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;let nx=x-drag.dx,ny=y-drag.dy;if(e.shiftKey){if(Math.abs(nx-state.pos[drag.k][0])>Math.abs(ny-state.pos[drag.k][1]))ny=state.pos[drag.k][1];else nx=state.pos[drag.k][0]}state.pos[drag.k]=[Math.max(2,Math.min(W-20,nx)),Math.max(12,Math.min(H-2,ny))];draw()});C.addEventListener('pointerup',()=>{if(drag){push();drag=null}});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();openExport();return}if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&state.selected){e.preventDefault();state.pos[state.selected][0]+=e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0;state.pos[state.selected][1]+=e.key==='ArrowUp'?-1:e.key==='ArrowDown'?1:0;draw()}});
function renderHistory(){const h=JSON.parse(localStorage.getItem('thumbly-pro-history')||'[]');$('history').innerHTML=h.map(x=>`<article class="history-card"><img src="${x.img}"><div class="meta"><strong>${esc(x.group)} · ${esc(x.title)}</strong><span>${esc(x.template)} / ${esc(x.date)}</span><div class="acts"><button data-del="${x.id}">削除</button><button data-show="${x.id}">再表示</button></div></div></article>`).join('');$('empty').style.display=h.length?'none':'block';document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{localStorage.setItem('thumbly-pro-history',JSON.stringify(h.filter(x=>x.id!=b.dataset.del)));renderHistory()});document.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>{const x=h.find(y=>y.id==b.dataset.show);if(x){document.querySelector('[data-page="editor"]').click();const im=new Image();im.onload=()=>{ctx.clearRect(0,0,W,H);ctx.drawImage(im,0,0,W,H)};im.src=x.img}})}
function saveHistory(data){let h=JSON.parse(localStorage.getItem('thumbly-pro-history')||'[]');h.unshift({id:Date.now(),img:data,title:state.texts.title,group:state.texts.group,template:state.t.n,date:new Date().toLocaleString('ja-JP')});try{localStorage.setItem('thumbly-pro-history',JSON.stringify(h.slice(0,40)))}catch{localStorage.setItem('thumbly-pro-history',JSON.stringify(h.slice(0,6)))}renderHistory()}
function openExport(){$('exportModal').classList.add('open')}function closeExport(){$('exportModal').classList.remove('open')}
function exportImage(){draw();const type=$('exportType').value,scale=+$('exportScale').value,q=+$('exportQuality').value/100;const out=document.createElement('canvas');out.width=W*scale;out.height=H*scale;const o=out.getContext('2d');o.imageSmoothingEnabled=true;o.imageSmoothingQuality='high';o.drawImage(C,0,0,out.width,out.height);const mime=type==='jpg'?'image/jpeg':type==='webp'?'image/webp':'image/png';out.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`thumbly-${Date.now()}.${type}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);const preview=out.toDataURL('image/jpeg',.82);saveHistory(preview);closeExport();toast(`${type.toUpperCase()} / ${scale}× で書き出しました`)},mime,q)}
$('export').onclick=openExport;$('exportOpen').onclick=openExport;$('exportClose').onclick=closeExport;$('exportCancel').onclick=closeExport;$('exportDo').onclick=exportImage;$('qualityOut').value='95%';$('exportQuality').oninput=e=>$('qualityOut').value=e.target.value+'%';
$('fit').onclick=()=>{state.photoMode='fit';draw()};$('fill').onclick=()=>{state.photoMode='fill';draw()};document.querySelectorAll('[data-bg]').forEach(b=>b.onclick=()=>{state.bg=b.dataset.bg;document.querySelectorAll('[data-bg]').forEach(x=>x.classList.toggle('active',x===b));draw()});$('gridBtn').onclick=()=>{state.grid=!state.grid;draw()};$('safeBtn').onclick=()=>{state.safe=!state.safe;draw()};$('zoomIn').onclick=()=>{state.zoom=Math.min(1.8,state.zoom+.1);$('canvasWrap').style.transform=`scale(${state.zoom})`;$('zoom').textContent=Math.round(state.zoom*100)+'%'};$('zoomOut').onclick=()=>{state.zoom=Math.max(.7,state.zoom-.1);$('canvasWrap').style.transform=`scale(${state.zoom})`;$('zoom').textContent=Math.round(state.zoom*100)+'%'};$('undo').onclick=undo;$('redo').onclick=redo;$('reset').onclick=()=>selectTemplate(2);$('duplicate').onclick=()=>{if(!state.selected)return;push();const nk=state.selected+'2';state.texts[nk]=state.texts[state.selected];state.pos[nk]=[state.pos[state.selected][0]+12,state.pos[state.selected][1]+12];state.layers.push(nk);state.selected=nk;renderLayers();draw()};$('deleteLayer').onclick=()=>{if(!state.selected)return;push();delete state.texts[state.selected];delete state.pos[state.selected];state.layers=state.layers.filter(k=>k!==state.selected);state.selected=null;syncUI();draw()};$('up').onclick=()=>{if(!state.selected)return;const i=state.layers.indexOf(state.selected);if(i<state.layers.length-1)[state.layers[i],state.layers[i+1]]=[state.layers[i+1],state.layers[i]];renderLayers();draw()};$('down').onclick=()=>{if(!state.selected)return;const i=state.layers.indexOf(state.selected);if(i>1)[state.layers[i],state.layers[i-1]]=[state.layers[i-1],state.layers[i]];renderLayers();draw()};
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(b.dataset.page==='editor'?'editorPage':'historyPage').classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===b));renderHistory()});$('clearHistory').onclick=()=>{if(confirm('作成履歴をすべて削除しますか？')){localStorage.removeItem('thumbly-pro-history');renderHistory()}};
function toast(s){const e=$('toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
inputEvents();renderDesign('color');selectTemplate(2);renderHistory();
