const $=id=>document.getElementById(id);
const C=$('canvas'),ctx=C.getContext('2d'),W=720,H=404;
const FONT_LIST=[
['Noto Sans KR','韓国語 / 標準'],['Black Han Sans','韓国語 / 極太'],['Do Hyeon','韓国語 / 番組系'],['Jua','韓国語 / 丸ゴ'],['Gowun Dodum','韓国語 / やわらか'],['Nanum Gothic','韓国語 / ゴシック'],['Nanum Myeongjo','韓国語 / 明朝'],['IBM Plex Sans KR','韓国語 / UI'],['Noto Serif KR','韓国語 / 明朝'],['Noto Sans JP','日本語 / ゴシック'],['Noto Serif JP','日本語 / 明朝'],['Inter','英数字 / UI'],['Montserrat','英数字 / 幾何学'],['Poppins','英数字 / 丸み'],['Outfit','英数字 / モダン'],['DM Sans','英数字 / クリーン'],['Roboto','英数字 / 定番'],['Roboto Condensed','英数字 / 縦長'],['Oswald','英数字 / 縦長強調'],['Barlow Condensed','英数字 / スポーツ'],['Bebas Neue','英数字 / 極太タイトル'],['Anton','英数字 / 極太'],['Archivo Black','英数字 / 強太'],['League Spartan','英数字 / 強太'],['Titillium Web','英数字 / テック'],['Ubuntu','英数字 / フレンドリー'],['Space Grotesk','英数字 / デザイン'],['Space Mono','英数字 / モノ'],['Archivo','英数字 / 放送系'],['Playfair Display','英数字 / セリフ']
];
const T=[
{id:1,n:'ONE TAKE CAM',f:'template-01.png',c:'#dcecff',font:'Noto Sans KR',text:{show:'ONE TAKE CAM',group:'Hearts2Hearts',title:'하츠투하츠',sub:'Hearts2Hearts'},pos:{show:[25,264],group:[22,341],title:[22,311],sub:[24,382]},sizes:{show:16,group:28,title:47,sub:18},style:'one'},
{id:2,n:'MBC KPOP',f:'template-02.png',c:'#2ab7ed',font:'Black Han Sans',text:{show:'MBC KPOP',group:'Hearts2Hearts',title:'카르멘',sub:'15-LOVE'},pos:{show:[39,47],group:[39,138],title:[39,186],sub:[40,247]},sizes:{show:19,group:32,title:48,sub:25},style:'mbc'},
{id:3,n:'SHOW! MUSIC CORE',f:'template-03.png',c:'#e64bd2',font:'Noto Sans KR',text:{show:'SHOW MUSIC CORE',group:'HEARTS2HEARTS · EP61',title:'15-LOVE',sub:''},pos:{show:[25,57],group:[17,315],title:[17,352],sub:[18,292]},sizes:{show:27,group:27,title:48,sub:22},style:'core'},
{id:4,n:'ZOOM FACE CAM',f:'template-04.png',c:'#4dbef0',font:'Noto Sans KR',text:{show:'FACE CAM',group:'Hearts2Hearts',title:'지우',sub:'Hearts2Hearts'},pos:{show:[24,264],group:[24,341],title:[24,311],sub:[24,382]},sizes:{show:16,group:27,title:47,sub:20},style:'zoom'},
{id:5,n:'MBC FULLCAM',f:'template-05.png',c:'#68bdf1',font:'Noto Sans KR',text:{show:'MBC KPOP',group:'Hearts2Hearts',title:'15-LOVE',sub:'Show! Music Core Fullcam'},pos:{show:[38,45],group:[38,342],title:[38,302],sub:[38,371]},sizes:{show:16,group:27,title:49,sub:21},style:'full'},
{id:6,n:'MUSIC BANK / 01',f:'template-06.png',c:'#f04bc6',font:'Montserrat',text:{show:'♪',group:'Hearts2Hearts',title:'15-LOVE',sub:''},pos:{show:[25,45],group:[25,340],title:[25,305],sub:[25,370]},sizes:{show:16,group:33,title:46,sub:22},style:'bank'},
{id:7,n:'MUSIC BANK / 02',f:'template-07.png',c:'#f04bc6',font:'Montserrat',text:{show:'MUSIC BANK',group:'Hearts2Hearts',title:'15-LOVE',sub:''},pos:{show:[26,47],group:[25,340],title:[25,306],sub:[25,370]},sizes:{show:16,group:33,title:46,sub:22},style:'bank2'},
{id:8,n:'FT SONG',f:'template-08.png',c:'#bfe2ed',font:'Inter',text:{show:'Hearts2Hearts',group:'FT Songs n°699',title:'',sub:''},pos:{show:[169,35],group:[167,383],title:[168,352],sub:[420,383]},sizes:{show:27,group:18,title:48,sub:18},style:'ft'},
{id:9,n:'MNET / MPD',f:'template-09.png',c:'#ef3d98',font:'Noto Sans KR',text:{show:'MPD직캠',group:'Hearts2Hearts',title:'15-LOVE',sub:''},pos:{show:[23,48],group:[24,382],title:[24,352],sub:[24,388]},sizes:{show:16,group:27,title:49,sub:22},style:'mpd'},
{id:10,n:'SHOW CHAMPION',f:'template-10.png',c:'#ff72a0',font:'Noto Sans KR',text:{show:'',group:'Hearts2Hearts',title:'15-LOVE',sub:''},pos:{show:[25,320],group:[25,350],title:[25,305],sub:[25,383]},sizes:{show:17,group:29,title:47,sub:22},style:'champ'}
];
const imgs={};T.forEach(t=>{const im=new Image();im.src='assets/templates/'+t.f;imgs[t.id]=im});
const photo=new Image();
const logoImgs={};
const logoMap={1:'01_ontake',2:'02_mbc',3:'03_showmusiccore',4:'04_zoom',5:'05_mbc',6:'06_musicbank',7:'07_musicbank',8:'08_ft',9:'09_mpd',10:'10_champ'};
Object.values(logoMap).forEach(n=>{const im=new Image();im.src='assets/logos/'+n+'.png';logoImgs[n]=im});
const state={doc:'Untitled thumbnail',template:T[1],photo:null,photoMode:'fill',mode:'edit',reference:false,grid:false,safe:false,zoom:1,theme:T[1].c,selected:null,selectedSet:new Set(),layers:[],objects:{},history:[],future:[],photoFx:{brightness:100,contrast:100,saturation:100,blur:0},compare:false};
let drag=null,dragBefore=null;
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function uid(prefix='layer'){return prefix+'-'+Math.random().toString(36).slice(2,9)}
function rgba(hex,a){const h=hex.replace('#','');const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16);return`rgba(${r},${g},${b},${a})`}
function saveSnapshot(){state.history.push(snapshot());if(state.history.length>60)state.history.shift();state.future=[]}
function snapshot(){return {template:state.template.id,theme:state.theme,photo:state.photo,photoMode:state.photoMode,mode:state.mode,grid:state.grid,safe:state.safe,objects:clone(state.objects),layers:clone(state.layers),photoFx:clone(state.photoFx)}}
function restore(s){state.template=T.find(t=>t.id===s.template)||T[1];state.theme=s.theme;state.photo=s.photo;state.photoMode=s.photoMode;state.mode=s.mode;state.grid=s.grid;state.safe=s.safe;state.objects=clone(s.objects);state.layers=clone(s.layers);state.photoFx=clone(s.photoFx||state.photoFx);state.selected=null;state.selectedSet.clear();if(state.photo){photo.onload=draw;photo.src=state.photo}syncAll();draw()}
function undo(){if(!state.history.length)return;state.future.push(snapshot());restore(state.history.pop());toast('元に戻しました')}
function redo(){if(!state.future.length)return;state.history.push(snapshot());restore(state.future.pop());toast('やり直しました')}
function baseText(id,role){const t=state.template;const o={id,type:'text',name:role==='title'?'メインタイトル':role==='group'?'グループ名':role==='show'?'番組名':'サブタイトル',role,text:t.text[role]||'',x:t.pos[role][0],y:t.pos[role][1],font:t.font,size:t.sizes[role]||22,weight:role==='title'?800:700,color:'#fff',opacity:1,rotation:0,scaleX:1,scaleY:1,tracking:0,lineHeight:1,shadow:true,stroke:role==='title',strokeWidth:role==='title'?2:0,strokeColor:'#000',glow:false,box:false,boxColor:'#000'};return o}
function resetTemplate(id){saveSnapshot();state.template=T.find(t=>t.id===id)||T[1];state.theme=state.template.c;state.objects={};state.layers=[];state.selected=null;state.selectedSet.clear();const photoObj={id:'photo',type:'photo',name:'写真',visible:true,locked:false,x:0,y:0,opacity:1,mode:state.photoMode};state.objects.photo=photoObj;state.layers.push('photo');['show','group','title','sub'].forEach(role=>{const o=baseText(uid(role),role);state.objects[o.id]=o;state.layers.push(o.id)});addTemplateDecoration();syncAll();draw();toast('テンプレートを適用しました')}
function addTemplateDecoration(){const s=state.template.style;const add=(type,props,name)=>{const o={id:uid(type),type,name,visible:true,locked:false,opacity:1,...props};state.objects[o.id]=o;state.layers.push(o.id);return o};
if(s==='mbc'){add('brand',{kind:'label',text:'MBC\nK-POP',x:39,y:27,size:14,font:'Inter',weight:800,color:'#fff'},'MBC K-POP ロゴ');add('shape',{shape:'bar',x:0,y:0,w:12,h:404,color:'#23b8ee'},'左アクセント')}
if(s==='core'){add('shape',{shape:'panel',x:0,y:0,w:245,h:88,color:state.theme,opacity:.9},'左カラーパネル');add('shape',{shape:'arc',x:550,y:-35,w:340,h:170,color:state.theme,opacity:.55},'右カーブ')}
if(s==='ft'){add('shape',{shape:'bar',x:351,y:0,w:36,h:404,color:'#d7eff7'},'センターバー')}
if(s==='mpd'){add('shape',{shape:'bar',x:0,y:0,w:720,h:12,color:state.theme},'上ライン');add('shape',{shape:'bar',x:0,y:392,w:720,h:12,color:state.theme},'下ライン')}
if(['bank','bank2'].includes(s)){add('shape',{shape:'line',x:0,y:8,w:720,h:3,color:'#fff'},'上フレーム');add('shape',{shape:'line',x:0,y:396,w:720,h:3,color:'#fff'},'下フレーム')}
if(s==='champ'){add('shape',{shape:'frame',x:8,y:8,w:704,h:388,color:'#fff',stroke:2,opacity:.8},'細枠')}
}
function drawPhoto(){if(!state.photo)return;const r=photo.width/photo.height,cr=W/H;let dw,dh;if(state.photoMode==='fit'){if(r>cr){dw=W;dh=W/r}else{dh=H;dw=H*r}}else{if(r>cr){dh=H;dw=H*r}else{dw=W;dh=W/r}}const x=(W-dw)/2,y=(H-dh)/2;ctx.save();const f=state.photoFx;ctx.filter=`brightness(${f.brightness}%) contrast(${f.contrast}%) saturate(${f.saturation}%) blur(${f.blur}px)`;ctx.drawImage(photo,x,y,dw,dh);ctx.restore()}
function drawOriginal(){const im=imgs[state.template.id];if(im.complete)ctx.drawImage(im,0,0,W,H)}
function fontSpec(o){return`${o.weight||700} ${o.size||20}px "${o.font||state.template.font}"`}
function measureText(o){ctx.font=fontSpec(o);const lines=String(o.text||'').split('\n');return{w:Math.max(...lines.map(x=>ctx.measureText(x).width),0),h:(o.size||20)*(o.lineHeight||1)*lines.length}}
function drawText(o){if(!o.visible||!o.text)return;ctx.save();ctx.globalAlpha=o.opacity??1;ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.scale(o.scaleX||1,o.scaleY||1);ctx.font=fontSpec(o);ctx.textBaseline='alphabetic';const lines=String(o.text).split('\n');const lh=(o.size||20)*(o.lineHeight||1);lines.forEach((line,i)=>{const y=i*lh;if(o.shadow){ctx.shadowColor='rgba(0,0,0,.48)';ctx.shadowBlur=Math.max(3,(o.size||20)*.08);ctx.shadowOffsetY=2}if(o.glow){ctx.shadowColor=rgba(state.theme,.9);ctx.shadowBlur=16}if(o.strokeWidth){ctx.lineWidth=o.strokeWidth;ctx.strokeStyle=o.strokeColor||'#000';ctx.strokeText(line,0,y)}ctx.shadowBlur=0;ctx.fillStyle=o.color||'#fff';drawTracked(line,0,y,o.tracking||0);if(o.box&&i===0){/* box is rendered behind via a second pass */}});if(o.box){const m=measureText(o);ctx.globalAlpha=(o.boxOpacity??.72);ctx.fillStyle=o.boxColor||'#000';ctx.globalCompositeOperation='destination-over';ctx.fillRect(-7,-m.h-7,m.w+14,m.h+14)}ctx.restore()}
function drawTracked(text,x,y,tracking){if(!tracking){ctx.fillText(text,x,y);return}let total=0;for(const ch of text)total+=ctx.measureText(ch).width+tracking;total-=tracking;let xx=x-total/2;for(const ch of text){ctx.fillText(ch,xx,y);xx+=ctx.measureText(ch).width+tracking}}
function drawShape(o){if(!o.visible)return;ctx.save();ctx.globalAlpha=o.opacity??1;ctx.fillStyle=o.color||state.theme;ctx.strokeStyle=o.color||'#fff';if(o.shape==='bar'||o.shape==='panel')ctx.fillRect(o.x,o.y,o.w,o.h);if(o.shape==='circle'){ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill()}if(o.shape==='arc'){ctx.beginPath();ctx.ellipse(o.x+o.w/2,o.y+o.h/2,o.w/2,o.h/2,0,0,Math.PI*2);ctx.fill()}if(o.shape==='line'){ctx.lineWidth=o.h||2;ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+o.w,o.y);ctx.stroke()}if(o.shape==='frame'){ctx.lineWidth=o.stroke||2;ctx.strokeRect(o.x,o.y,o.w,o.h)}if(o.shape==='gradient'){const g=ctx.createLinearGradient(o.x,o.y,o.x+o.w,o.y);g.addColorStop(0,o.color||state.theme);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(o.x,o.y,o.w,o.h)}if(o.shape==='dots'){for(let x=o.x;x<o.x+o.w;x+=16){ctx.beginPath();ctx.arc(x,o.y,1.5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x,o.y+o.h,1.5,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function drawImageLayer(o){if(!o.visible)return;const im=logoImgs[o.asset];if(!im||!im.complete)return;ctx.save();ctx.globalAlpha=o.opacity??1;ctx.drawImage(im,o.x,o.y,o.w||im.width,o.h||im.height);ctx.restore()}
function drawBrand(o){if(!o.visible)return;ctx.save();ctx.globalAlpha=o.opacity??1;ctx.fillStyle=o.color||'#fff';ctx.font=`${o.weight||800} ${o.size||14}px "${o.font||'Inter'}"`;const lines=String(o.text||'').split('\n');lines.forEach((x,i)=>ctx.fillText(x,o.x,o.y+i*(o.size||14)*1.05));ctx.restore()}
function renderLayer(id){const o=state.objects[id];if(!o||o.visible===false)return;if(o.type==='group'){o.children.forEach(renderLayer);return}if(o.type==='photo')return;if(o.type==='text')drawText(o);if(o.type==='shape')drawShape(o);if(o.type==='brand')drawBrand(o);if(o.type==='image')drawImageLayer(o);if(o.type==='effect')drawEffect(o)}
function drawEffect(o){if(!o.visible)return;ctx.save();ctx.globalAlpha=o.opacity??1;if(o.effect==='vignette'){const g=ctx.createRadialGradient(W/2,H/2,80,W/2,H/2,450);g.addColorStop(0,'transparent');g.addColorStop(1,'rgba(0,0,0,.48)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}if(o.effect==='noise'){for(let i=0;i<5000;i++){ctx.fillStyle=`rgba(255,255,255,${Math.random()*.045})`;ctx.fillRect(Math.random()*W,Math.random()*H,1,1)}}if(o.effect==='scan'){ctx.fillStyle='rgba(255,255,255,.08)';for(let y=0;y<H;y+=4)ctx.fillRect(0,y,W,1)}if(o.effect==='glow'){const g=ctx.createRadialGradient(W*.75,H*.25,10,W*.75,H*.25,220);g.addColorStop(0,rgba(state.theme,.35));g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}ctx.restore()}
function guides(){if(state.grid){ctx.save();ctx.strokeStyle='rgba(120,120,180,.15)';for(let x=0;x<=W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<=H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.restore()}if(state.safe){ctx.save();ctx.setLineDash([6,5]);ctx.strokeStyle='rgba(235,80,120,.7)';ctx.strokeRect(36,24,W-72,H-48);ctx.restore()}}
function bounds(o){if(o.type==='text'){const m=measureText(o);return{x:o.x-8,y:o.y-m.h-8,w:m.w+16,h:m.h+16}}if(o.type==='shape'){if(o.shape==='circle')return{x:o.x-o.r,y:o.y-o.r,w:o.r*2,h:o.r*2};return{x:o.x,y:o.y,w:o.w||20,h:o.h||20}}if(o.type==='brand'){return{x:o.x-4,y:o.y-(o.size||14)-4,w:ctx.measureText(o.text||'').width+8,h:(o.size||14)+8}}if(o.type==='image'){return{x:o.x,y:o.y,w:o.w||60,h:o.h||30}}if(o.type==='photo')return{x:0,y:0,w:W,h:H};return{x:0,y:0,w:W,h:H}}
function hit(x,y){for(let i=state.layers.length-1;i>=0;i--){const id=state.layers[i],o=state.objects[id];if(!o||o.visible===false||o.locked)continue;if(o.type==='group'){for(let j=o.children.length-1;j>=0;j--){const c=state.objects[o.children[j]];if(c&&inside(bounds(c),x,y))return c.id}}else if(inside(bounds(o),x,y))return id}return null}
function inside(b,x,y){return x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h}
function selectionBox(o){if(!o||o.type==='photo')return;const b=bounds(o);ctx.save();ctx.strokeStyle='#7771f2';ctx.setLineDash([5,4]);ctx.lineWidth=1;ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.setLineDash([]);ctx.fillStyle='#7771f2';[[b.x,b.y],[b.x+b.w,b.y],[b.x,b.y+b.h],[b.x+b.w,b.y+b.h]].forEach(([x,y])=>ctx.fillRect(x-3,y-3,6,6));ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);if(state.mode==='reference'||state.reference){drawOriginal();$('compareOverlay').classList.add('show')}else{$('compareOverlay').classList.remove('show');if(state.photo)drawPhoto();else{ctx.fillStyle='#e8ebf1';ctx.fillRect(0,0,W,H)}state.layers.forEach(renderLayer);guides();if(state.selected){const o=state.objects[state.selected];if(o)selectionBox(o)}}if(state.compare){ctx.save();ctx.globalAlpha=.62;drawOriginal();ctx.restore();$('compareOverlay').classList.add('show')} }
function renderTemplates(){const host=$('leftContent');host.innerHTML=`<div class="left-inner"><div class="eyebrow">TEMPLATES</div><div class="section-title"><h3>番組テンプレート</h3><small>10 styles</small></div><div class="template-list">${T.map(t=>`<button class="template-card ${t.id===state.template.id?'active':''}" data-template="${t.id}"><img src="assets/templates/${t.f}"><span class="check">✓</span><div class="tc-meta"><strong>${esc(t.n)}</strong><span>${t.font}</span></div></button>`).join('')}</div></div>`;host.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>resetTemplate(+b.dataset.template))}
function renderElements(){const host=$('leftContent');host.innerHTML=`<div class="left-inner"><div class="eyebrow">ELEMENTS</div><div class="section-title"><h3>ドラッグ / 追加</h3><small>DESIGN KIT</small></div><div class="element-grid"><button class="element-btn" data-add="text"><b>T テキスト</b><small>見出しを追加</small></button><button class="element-btn" data-add="gradient"><b>◐ グラデーション</b><small>光の帯を追加</small></button><button class="element-btn" data-add="frame"><b>□ フレーム</b><small>放送系の枠</small></button><button class="element-btn" data-add="dots"><b>•• ドット</b><small>ハーフトーン</small></button><button class="element-btn" data-add="glow"><b>✦ Glow</b><small>発光レイヤー</small></button><button class="element-btn" data-add="vignette"><b>◌ Vignette</b><small>周辺減光</small></button><button class="element-btn" data-add="scan"><b>≡ Scanlines</b><small>放送モニター感</small></button><button class="element-btn" data-add="noise"><b>· Noise</b><small>フィルム質感</small></button><button class="element-btn" data-add="logo"><b>▣ ロゴ</b><small>テンプレートのロゴ</small></button></div><div class="section-title"><h3>カラーパレット</h3></div><div class="palette" id="palette"></div><div class="section-title"><h3>保存済みテキストスタイル</h3></div><div id="stylesSaved" class="font-list"></div></div>`;host.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addElement(b.dataset.add));const colors=['#bdefff','#d8c8ff','#ffb7d5','#c7f5e8','#ffd7a8','#f8a8d0','#b7d5ff','#fff2a6','#1f2430','#ffffff'];$('palette').innerHTML=colors.map(c=>`<button class="swatch" style="background:${c}" data-color="${c}" title="${c}"></button>`).join('');$('palette').querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.color;toast('テーマカラーを変更');draw()});renderSavedStyles()}
function renderUploads(){const host=$('leftContent');host.innerHTML=`<div class="left-inner"><div class="eyebrow">PHOTO</div><div class="section-title"><h3>写真を差し替え</h3><small>JPG / PNG / WEBP</small></div><label class="dropzone" id="dropzone"><input id="photoInput" type="file" accept="image/*"><div class="plus">＋</div><strong>ここに写真をドロップ</strong><small>クリックしてファイルを選択</small></label><div class="mini-row"><button class="mini-btn ${state.photoMode==='fit'?'active':''}" data-photo-mode="fit">全体表示</button><button class="mini-btn ${state.photoMode==='fill'?'active':''}" data-photo-mode="fill">全面表示</button></div><div class="section-title"><h3>写真補正</h3></div><div id="photoControls"></div><div class="section-title"><h3>自動レイアウト</h3></div><button class="element-btn" id="autoLayout"><b>✦ いい感じに配置</b><small>顔検出 / フォールバック中央配置</small></button></div>`;bindPhotoUpload();renderPhotoControls()}
function renderPhotoControls(){const f=state.photoFx;$('photoControls').innerHTML=['brightness','contrast','saturation','blur'].map(k=>{const labels={brightness:'明るさ',contrast:'コントラスト',saturation:'彩度',blur:'ぼかし'};const min=k==='blur'?0:50,max=k==='blur'?10:180,step=k==='blur'?.5:1,val=f[k];return`<div class="field"><span>${labels[k]} <output>${val}${k==='blur'?'px':'%'}</output></span><input data-photo-fx="${k}" type="range" min="${min}" max="${max}" step="${step}" value="${val}"></div>`}).join('');document.querySelectorAll('[data-photo-fx]').forEach(i=>i.oninput=e=>{state.photoFx[e.target.dataset.photoFx]=+e.target.value;draw();});$('autoLayout').onclick=autoLayout}
function bindPhotoUpload(){const dz=$('dropzone'),inp=$('photoInput');inp.onchange=e=>loadPhoto(e.target.files[0]);['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>loadPhoto(e.dataTransfer.files[0]));document.querySelectorAll('[data-photo-mode]').forEach(b=>b.onclick=()=>{state.photoMode=b.dataset.photoMode;state.objects.photo.mode=state.photoMode;renderUploads();draw()})}
function loadPhoto(file){if(!file)return;const r=new FileReader();r.onload=()=>{state.photo=r.result;photo.onload=()=>{draw();toast('写真を読み込みました')};photo.src=r.result};r.readAsDataURL(file)}
function autoLayout(){saveSnapshot();const title=state.layers.map(id=>state.objects[id]).find(o=>o&&o.type==='text'&&o.role==='title');const group=state.layers.map(id=>state.objects[id]).find(o=>o&&o.type==='text'&&o.role==='group');if(!title)return;const apply=x=>{title.x=x>W/2?24:W-270;group&&(group.x=title.x);};if('FaceDetector'in window&&state.photo){try{const fd=new FaceDetector({fastMode:true,maxDetectedFaces:1});fd.detect(photo).then(fs=>{if(fs[0])apply(fs[0].boundingBox.x+fs[0].boundingBox.width/2);else apply(W/2);draw();toast('顔位置から自動配置しました')}).catch(()=>{apply(W/2);draw();toast('自動配置しました')})}catch{apply(W/2);draw()}}else{apply(W/2);draw();toast('自動配置しました')}}
function addElement(kind){saveSnapshot();let o;if(kind==='text'){o={id:uid('text'),type:'text',name:'新しいテキスト',role:'custom',text:'NEW TITLE',x:40,y:90,font:'Montserrat',size:42,weight:800,color:'#fff',opacity:1,rotation:0,scaleX:1,scaleY:1,tracking:0,lineHeight:1,shadow:true,stroke:false,strokeWidth:0,strokeColor:'#000',glow:false,box:false}}else if(['gradient','frame','dots'].includes(kind)){o={id:uid('shape'),type:'shape',name:kind==='gradient'?'グラデーション':kind==='frame'?'フレーム':'ドット',shape:kind,x:0,y:0,w:W,h:H,color:state.theme,opacity:kind==='gradient'?.25:.9,stroke:2}}else if(kind==='logo'){const asset=logoMap[state.template.id];const im=logoImgs[asset];o={id:uid('image'),type:'image',name:'番組ロゴ',asset,x:20,y:16,w:im?.width?Math.min(170,im.width):100,h:im?.height?Math.min(70,im.height):35,opacity:1,visible:true,locked:false}}else{o={id:uid('effect'),type:'effect',name:{glow:'Glow',vignette:'Vignette',scan:'Scanlines',noise:'Noise'}[kind],effect:kind,opacity:1,visible:true,locked:false}}state.objects[o.id]=o;state.layers.push(o.id);state.selected=o.id;state.selectedSet=new Set([o.id]);renderLayers();renderProperties();draw()}
function layerLabel(o){return o?.name||'レイヤー'}
function renderLayers(){const host=$('layersPanel');const visibleIds=new Set(state.layers);host.innerHTML=state.layers.slice().reverse().map(id=>{const o=state.objects[id];if(!o)return'';return`<div class="layer-row ${state.selectedSet.has(id)?'selected':''}" data-layer="${id}"><button class="eye" data-eye="${id}">${o.visible===false?'○':'●'}</button><button data-lock="${id}">${o.locked?'🔒':'◇'}</button><span class="layer-thumb">${o.type==='text'?'T':o.type==='photo'?'▣':o.type==='group'?'▤':o.type==='effect'?'✦':'□'}</span><div><div class="layer-name">${esc(layerLabel(o))}</div><div class="layer-kind">${o.type.toUpperCase()}</div></div><button data-more="${id}">⋯</button></div>`}).join('');host.querySelectorAll('[data-layer]').forEach(r=>r.onclick=e=>{const id=r.dataset.layer;if(e.shiftKey){state.selectedSet.has(id)?state.selectedSet.delete(id):state.selectedSet.add(id);state.selected=[...state.selectedSet][0]||null}else{state.selected=id;state.selectedSet=new Set([id])}renderLayers();renderProperties();draw()});host.querySelectorAll('[data-eye]').forEach(b=>b.onclick=e=>{e.stopPropagation();const o=state.objects[b.dataset.eye];o.visible=o.visible===false;renderLayers();draw()});host.querySelectorAll('[data-lock]').forEach(b=>b.onclick=e=>{e.stopPropagation();const o=state.objects[b.dataset.lock];o.locked=!o.locked;renderLayers()});host.querySelectorAll('[data-more]').forEach(b=>b.onclick=e=>{e.stopPropagation();renameLayer(b.dataset.more)})}
function renameLayer(id){const o=state.objects[id];const n=prompt('レイヤー名',o.name);if(n){o.name=n;renderLayers();renderProperties()}}
function renderProperties(){const o=state.selected?state.objects[state.selected]:null;$('selectedName').textContent=o?layerLabel(o):'未選択';const p=$('propertiesBody');if(!o){p.innerHTML='<div class="empty-prop">レイヤーを選択すると、ここにプロパティが表示されます。<br>キャンバス上をクリックして直接選択できます。</div>';return}if(o.type==='text')renderTextProperties(o,p);else if(o.type==='photo')renderPhotoProperties(o,p);else if(o.type==='shape')renderShapeProperties(o,p);else if(o.type==='effect')renderEffectProperties(o,p);else if(o.type==='image')renderImageProperties(o,p);else p.innerHTML='<div class="empty-prop">グループはレイヤーパネルから操作できます。</div>'}
function fieldRange(label,id,value,min,max,step='1',suffix=''){return`<div class="field"><span>${label}<output id="out-${id}">${value}${suffix}</output></span><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></div>`}
function renderTextProperties(o,p){p.innerHTML=`<div class="prop-body"><div class="prop-section"><h4>Text</h4><div class="field"><span>テキスト</span><input id="pText" type="text" value="${esc(o.text)}"></div><div class="field"><span>フォント</span><select id="pFont">${FONT_LIST.map(f=>`<option value="${f[0]}" ${o.font===f[0]?'selected':''}>${f[0]} — ${f[1]}</option>`).join('')}</select></div><div class="two"><div class="field"><span>サイズ</span><input id="pSize" type="number" value="${o.size}" min="6" max="160"></div><div class="field"><span>太さ</span><select id="pWeight">${[300,400,500,600,700,800,900].map(x=>`<option ${x===o.weight?'selected':''}>${x}</option>`).join('')}</select></div></div></div><div class="prop-section"><h4>Color & Effects</h4><div class="two"><div class="field"><span>文字色</span><div class="color-input"><input id="pColor" type="color" value="${o.color}"><span>${o.color}</span></div></div><div class="field"><span>縁取り</span><div class="color-input"><input id="pStrokeColor" type="color" value="${o.strokeColor||'#000000'}"><span>Stroke</span></div></div></div><div class="toggle-row"><button class="toggle ${o.shadow?'active':''}" data-toggle="shadow">影</button><button class="toggle ${o.stroke?'active':''}" data-toggle="stroke">縁取り</button><button class="toggle ${o.glow?'active':''}" data-toggle="glow">発光</button><button class="toggle ${o.box?'active':''}" data-toggle="box">背景</button></div></div><div class="prop-section"><h4>Transform</h4>${fieldRange('回転','pRot',o.rotation,-180,180,.5,'°')}${fieldRange('不透明度','pOpacity',Math.round(o.opacity*100),0,100,1,'%')}${fieldRange('字間','pTracking',o.tracking,-5,20,.5)}<div class="two"><div class="field"><span>X</span><input id="pX" type="number" value="${Math.round(o.x)}"></div><div class="field"><span>Y</span><input id="pY" type="number" value="${Math.round(o.y)}"></div></div><div class="two"><div class="field"><span>横伸縮</span><input id="pSX" type="number" value="${o.scaleX}" step=".01"></div><div class="field"><span>縦伸縮</span><input id="pSY" type="number" value="${o.scaleY}" step=".01"></div></div></div><div class="prop-actions"><button class="small-action" id="saveStyle">この文字スタイルを保存</button><button class="small-action" id="duplicateText">複製</button></div></div>`;bindTextProps(o)}
function bindTextProps(o){const on=(id,fn)=>$(id).addEventListener('input',e=>{fn(e.target.value);draw()});on('pText',v=>o.text=v);on('pFont',v=>o.font=v);on('pSize',v=>o.size=+v);on('pWeight',v=>o.weight=+v);on('pColor',v=>o.color=v);on('pStrokeColor',v=>o.strokeColor=v);on('pRot',v=>o.rotation=+v);on('pOpacity',v=>{o.opacity=+v/100;$('out-pOpacity').textContent=v+'%'});on('pTracking',v=>{o.tracking=+v;$('out-pTracking').textContent=v});on('pX',v=>o.x=+v);on('pY',v=>o.y=+v);on('pSX',v=>o.scaleX=+v);on('pSY',v=>o.scaleY=+v);document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{o[b.dataset.toggle]=!o[b.dataset.toggle];renderProperties();draw()});$('saveStyle').onclick=()=>{const styles=JSON.parse(localStorage.getItem('thumbly-styles')||'[]');styles.unshift({id:Date.now(),name:o.name,font:o.font,size:o.size,weight:o.weight,color:o.color,stroke:o.stroke,strokeWidth:o.strokeWidth,strokeColor:o.strokeColor,shadow:o.shadow,glow:o.glow});localStorage.setItem('thumbly-styles',JSON.stringify(styles.slice(0,20)));renderElements();toast('文字スタイルを保存しました')};$('duplicateText').onclick=()=>duplicateLayer()}
function renderPhotoProperties(o,p){p.innerHTML=`<div class="prop-body"><div class="prop-section"><h4>Photo</h4><div class="toggle-row"><button class="toggle ${state.photoMode==='fill'?'active':''}" id="pFill">全面表示</button><button class="toggle ${state.photoMode==='fit'?'active':''}" id="pFit">全体表示</button></div></div><div class="prop-section"><h4>Adjust</h4>${fieldRange('明るさ','ppB',state.photoFx.brightness,50,180,1,'%')}${fieldRange('コントラスト','ppC',state.photoFx.contrast,50,180,1,'%')}${fieldRange('彩度','ppS',state.photoFx.saturation,0,180,1,'%')}${fieldRange('ぼかし','ppBlur',state.photoFx.blur,0,10,.5,'px')}</div></div>`;[['ppB','brightness'],['ppC','contrast'],['ppS','saturation'],['ppBlur','blur']].forEach(([id,k])=>$(id).oninput=e=>{state.photoFx[k]=+e.target.value;$(id).previousElementSibling.querySelector('output').textContent=e.target.value+(k==='blur'?'px':'%');draw()});$('pFill').onclick=()=>{state.photoMode='fill';renderProperties();draw()};$('pFit').onclick=()=>{state.photoMode='fit';renderProperties();draw()}}
function renderShapeProperties(o,p){p.innerHTML=`<div class="prop-body"><div class="prop-section"><h4>Shape</h4><div class="field"><span>色</span><div class="color-input"><input id="sColor" type="color" value="${o.color||state.theme}"><span>COLOR</span></div></div>${fieldRange('不透明度','sOpacity',Math.round((o.opacity??1)*100),0,100,1,'%')}<div class="two"><div class="field"><span>X</span><input id="sX" type="number" value="${o.x||0}"></div><div class="field"><span>Y</span><input id="sY" type="number" value="${o.y||0}"></div></div></div></div>`;const bind=(id,fn)=>$(id).oninput=e=>{fn(e.target.value);draw()};bind('sColor',v=>o.color=v);bind('sOpacity',v=>o.opacity=+v/100);bind('sX',v=>o.x=+v);bind('sY',v=>o.y=+v)}

function renderImageProperties(o,p){p.innerHTML=`<div class="prop-body"><div class="prop-section"><h4>Image</h4><div class="field"><span>不透明度</span><input id="iOpacity" type="range" min="0" max="100" value="${Math.round((o.opacity??1)*100)}"></div><div class="two"><div class="field"><span>X</span><input id="iX" type="number" value="${Math.round(o.x)}"></div><div class="field"><span>Y</span><input id="iY" type="number" value="${Math.round(o.y)}"></div></div><div class="two"><div class="field"><span>幅</span><input id="iW" type="number" value="${Math.round(o.w)}"></div><div class="field"><span>高さ</span><input id="iH" type="number" value="${Math.round(o.h)}"></div></div></div></div>`;[['iOpacity',v=>o.opacity=+v/100],['iX',v=>o.x=+v],['iY',v=>o.y=+v],['iW',v=>o.w=+v],['iH',v=>o.h=+v]].forEach(([id,fn])=>$(id).oninput=e=>{fn(e.target.value);draw()})}
function renderEffectProperties(o,p){p.innerHTML=`<div class="prop-body"><div class="prop-section"><h4>Effect</h4>${fieldRange('不透明度','eOpacity',Math.round((o.opacity??1)*100),0,100,1,'%')}</div><div class="prop-section"><button class="small-action" id="effectDelete">このエフェクトを削除</button></div></div>`;$('eOpacity').oninput=e=>{o.opacity=+e.target.value/100;draw()};$('effectDelete').onclick=()=>deleteSelected()}
function renderSavedStyles(){const host=$('stylesSaved');if(!host)return;const s=JSON.parse(localStorage.getItem('thumbly-styles')||'[]');host.innerHTML=s.length?s.slice(0,6).map(x=>`<button class="font-choice" data-style="${x.id}"><b style="font-family:'${x.font}'">Aa ${esc(x.name)}</b><small>${x.font} · ${x.size}px</small></button>`).join(''):'<div style="font-size:9px;color:#999">右パネルから保存するとここに表示。</div>';host.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{const st=s.find(x=>x.id==b.dataset.style),o=state.objects[state.selected];if(st&&o?.type==='text'){Object.assign(o,st);renderProperties();draw()}})}
function duplicateLayer(){if(!state.selected)return;saveSnapshot();const o=state.objects[state.selected];const n=clone(o);n.id=uid(o.type);n.name=o.name+' コピー';n.x=(n.x||0)+14;n.y=(n.y||0)+14;state.objects[n.id]=n;const i=state.layers.indexOf(state.selected);state.layers.splice(i+1,0,n.id);state.selected=n.id;state.selectedSet=new Set([n.id]);renderLayers();renderProperties();draw()}
function deleteSelected(){if(!state.selected)return;saveSnapshot();const ids=[...state.selectedSet];ids.forEach(id=>{delete state.objects[id];state.layers=state.layers.filter(x=>x!==id)});state.selected=null;state.selectedSet.clear();renderLayers();renderProperties();draw()}
function moveLayer(dir){if(!state.selected)return;saveSnapshot();const i=state.layers.indexOf(state.selected),j=dir==='up'?i+1:i-1;if(j<0||j>=state.layers.length)return;[state.layers[i],state.layers[j]]=[state.layers[j],state.layers[i]];renderLayers();draw()}
function groupSelected(){const ids=[...state.selectedSet].filter(id=>state.layers.includes(id));if(ids.length<1)return;saveSnapshot();const gid=uid('group');state.objects[gid]={id:gid,type:'group',name:'グループ',children:ids,visible:true,locked:false};state.layers=state.layers.filter(id=>!ids.includes(id));state.layers.push(gid);state.selected=gid;state.selectedSet=new Set([gid]);renderLayers();renderProperties();draw();toast('グループを作成しました')}
function syncAll(){renderTemplates();renderLayers();renderProperties();$('templateLabel').textContent=state.template.n;$('docName').firstChild.textContent=state.doc+' ';renderLeftActive();}
function renderLeftActive(){document.querySelectorAll('.panel-tab').forEach(b=>b.classList.toggle('active',b.dataset.left===window._leftTab));if(window._leftTab==='elements')renderElements();else if(window._leftTab==='uploads')renderUploads();else renderTemplates()}
function showLeft(tab){window._leftTab=tab;renderLeftActive()}
function renderProjects(){const h=JSON.parse(localStorage.getItem('thumbly-projects')||'[]');$('projectGrid').innerHTML=h.length?h.map(x=>`<article class="project-card"><img src="${x.preview}"><div class="pc-meta"><strong>${esc(x.name)}</strong><small>${esc(x.template)} · ${esc(x.date)}</small><div class="pc-actions"><button data-load="${x.id}">開く</button><button data-remove="${x.id}">削除</button></div></div></article>`).join(''):'<div style="grid-column:1/-1;color:#999;font-size:11px;padding:30px">まだ保存されたプロジェクトはありません。</div>';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const a=h.filter(x=>x.id!=b.dataset.remove);localStorage.setItem('thumbly-projects',JSON.stringify(a));renderProjects()});document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const x=h.find(y=>y.id==b.dataset.load);if(!x)return;loadProjectData(x.data);$('historyModal').classList.remove('open')})}
function saveProject(){const data=snapshot();let a=JSON.parse(localStorage.getItem('thumbly-projects')||'[]');const preview=renderToDataURL('image/jpeg',.82,1);a.unshift({id:Date.now(),name:state.doc,template:state.template.n,date:new Date().toLocaleString('ja-JP'),preview,data});try{localStorage.setItem('thumbly-projects',JSON.stringify(a.slice(0,20)))}catch{localStorage.setItem('thumbly-projects',JSON.stringify(a.slice(0,5)))}toast('プロジェクトを保存しました')}
function loadProjectData(data){restore(data);state.doc='Restored thumbnail';syncAll();draw();toast('プロジェクトを読み込みました')}
function renderToDataURL(mime='image/png',quality=.95,scale=1){const out=document.createElement('canvas');out.width=W*scale;out.height=H*scale;const o=out.getContext('2d');o.imageSmoothingQuality='high';o.scale(scale,scale);const oldSel=state.selected;state.selected=null;const oldMode=state.mode;state.mode='edit';draw();o.drawImage(C,0,0,W,H);state.selected=oldSel;state.mode=oldMode;return out.toDataURL(mime,quality)}
function exportImage(){const type=$('exportType').value,scale=+$('exportScale').value,q=+$('exportQuality').value/100;const data=renderToDataURL(type==='jpg'?'image/jpeg':type==='webp'?'image/webp':'image/png',q,scale);const a=document.createElement('a');a.href=data;a.download=`thumbly-${Date.now()}.${type}`;a.click();saveHistory(data);closeModal('exportModal');toast(`${type.toUpperCase()} · ${scale}× で書き出しました`)}
function saveHistory(data){let h=JSON.parse(localStorage.getItem('thumbly-history')||'[]');h.unshift({id:Date.now(),img:data,name:state.doc,template:state.template.n,date:new Date().toLocaleString('ja-JP')});try{localStorage.setItem('thumbly-history',JSON.stringify(h.slice(0,30)))}catch{localStorage.setItem('thumbly-history',JSON.stringify(h.slice(0,5)))}}
function openModal(id){$(id).classList.add('open');if(id==='historyModal')renderProjects();if(id==='variantModal')renderVariants()}
function closeModal(id){$(id).classList.remove('open')}
function renderVariants(){const base=snapshot(),variants=[['SOFT BLUE','#bdefff','Noto Sans KR'],['NEON PINK','#ed5cc8','Montserrat'],['LAVENDER','#d8c8ff','Poppins'],['CLEAN WHITE','#ffffff','Inter']];const host=$('variantGrid');host.innerHTML=variants.map((v,i)=>`<article class="variant-card"><img id="variant-${i}" src=""><div class="pc-meta"><strong>${v[0]}</strong><small>${v[2]}</small><div class="pc-actions"><button data-apply-variant="${i}">この案を採用</button></div></div></article>`).join('');variants.forEach((v,i)=>{const s=clone(base);s.theme=v[1];Object.values(s.objects).forEach(o=>{if(o.type==='text'){o.font=v[2];if(o.role==='title')o.size+=i===1?5:0;o.color=i===3?'#20212a':'#fff'}});restore(s);$('variant-'+i).src=renderToDataURL('image/jpeg',.8,1);});restore(base);document.querySelectorAll('[data-apply-variant]').forEach(b=>b.onclick=()=>{const i=+b.dataset.applyVariant;const s=clone(base),v=variants[i];s.theme=v[1];Object.values(s.objects).forEach(o=>{if(o.type==='text'){o.font=v[2];o.color=i===3?'#20212a':'#fff'}});restore(s);closeModal('variantModal');toast('バリエーションを適用しました')})}
function renameDoc(){const n=prompt('プロジェクト名',state.doc);if(n){state.doc=n;syncAll()}}
function toast(s){const e=$('toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
C.addEventListener('pointerdown',e=>{const r=C.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height,id=hit(x,y);if(id){state.selected=id;state.selectedSet=new Set([id]);const o=state.objects[id];drag={id,dx:x-(o.x||0),dy:y-(o.y||0)};dragBefore=snapshot();C.setPointerCapture(e.pointerId);renderLayers();renderProperties();draw()}else{state.selected=null;state.selectedSet.clear();renderLayers();renderProperties();draw()}});
C.addEventListener('pointermove',e=>{if(!drag)return;const r=C.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height,o=state.objects[drag.id];if(!o)return;let nx=x-drag.dx,ny=y-drag.dy;if(e.shiftKey){const ox=o.x,oy=o.y;Math.abs(nx-ox)>=Math.abs(ny-oy)?ny=oy:nx=ox}o.x=Math.round(nx);o.y=Math.round(ny);draw();});
C.addEventListener('pointerup',()=>{if(drag){state.history.push(dragBefore);if(state.history.length>60)state.history.shift();state.future=[];drag=null}});
window.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){if(tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT')return;e.preventDefault();duplicateLayer();return}if(tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT')return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&state.selected){e.preventDefault();const o=state.objects[state.selected];o.x+=(e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0);o.y+=(e.key==='ArrowUp'?-1:e.key==='ArrowDown'?1:0);draw()}});
$('canvas').ondblclick=()=>{if(state.selected&&state.objects[state.selected]?.type==='text'){$('pText')?.focus();$('pText')?.select()}};
document.querySelectorAll('.panel-tab').forEach(b=>b.onclick=()=>showLeft(b.dataset.left));$('addText').onclick=()=>addElement('text');$('addGroup').onclick=groupSelected;$('layerUp').onclick=()=>moveLayer('up');$('layerDown').onclick=()=>moveLayer('down');$('layerDuplicate').onclick=duplicateLayer;$('layerDelete').onclick=deleteSelected;$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('saveProject').onclick=saveProject;$('newProject').onclick=()=>{if(confirm('新規プロジェクトを作成しますか？')){state.doc='Untitled thumbnail';state.photo=null;state.photoMode='fill';resetTemplate(2)}};$('renameDoc').onclick=renameDoc;$('exportBtn').onclick=()=>openModal('exportModal');$('projectsBtn').onclick=()=>openModal('historyModal');$('doExport').onclick=exportImage;$('qualityOut').textContent='95%';$('exportQuality').oninput=e=>$('qualityOut').textContent=e.target.value+'%';document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$('compareBtn').onclick=()=>{state.compare=!state.compare;draw()};$('referenceBtn').onclick=()=>{state.mode=state.mode==='reference'?'edit':'reference';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));draw()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;draw()});$('variantBtn').onclick=()=>openModal('variantModal');$('gridBtn').onclick=()=>{state.grid=!state.grid;draw()};$('safeBtn').onclick=()=>{state.safe=!state.safe;draw()};$('zoomIn').onclick=()=>{state.zoom=Math.min(1.8,state.zoom+.1);$('canvas').style.transform=`scale(${state.zoom})`;$('zoomLabel').textContent=Math.round(state.zoom*100)+'%'};$('zoomOut').onclick=()=>{state.zoom=Math.max(.7,state.zoom-.1);$('canvas').style.transform=`scale(${state.zoom})`;$('zoomLabel').textContent=Math.round(state.zoom*100)+'%'};
window._leftTab='templates';resetTemplate(2);syncAll();
