const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const A='assets/';
const templates=[
{id:'scfan',n:'SHOW CHAMPION｜チッケム',f:'SHOW CHANPION チッケム テンプレ(2).jpg',logo:'SHOW CHANPION チッケム.svg',font:'Noto Sans KR',style:'scfan',x:.035,y:.78,align:'left'},
{id:'inkfan',n:'人気歌謡｜チッケム',f:'人気歌謡 チッケム テンプレ(2).jpg',logo:'人気歌謡 チッケム.svg',font:'Inter',style:'inkfan',x:.035,y:.74,align:'left'},
{id:'ink',n:'人気歌謡',f:'人気歌謡 テンプレ(2).jpg',logo:'人気歌謡.svg',font:'Inter',style:'ink',x:.03,y:.74,align:'left'},
{id:'mcfan',n:'音楽中心｜チッケム',f:'音楽中心 チッケム テンプレ(2).jpg',logo:'音楽中心 チッケム(1).svg',font:'Noto Sans KR',style:'mcfan',x:.04,y:.73,align:'left'},
{id:'mc',n:'音楽中心',f:'音楽中心 テンプレ(2).jpg',logo:'音楽中心(1).svg',font:'Noto Sans KR',style:'mc',x:.05,y:.78,align:'left'},
{id:'mb1',n:'MUSIC BANK｜タイプ 01',f:'MUSICBANK① テンプレ(2).jpg',logo:'MUSICBANK①.svg',font:'Inter',style:'mb1',x:.035,y:.72,align:'left'},
{id:'mb2',n:'MUSIC BANK｜タイプ 02',f:'MUSICBANK② テンプレ(2).jpg',logo:'MUSICBANK②.svg',font:'Inter',style:'mb2',x:.035,y:.72,align:'left'},
{id:'mb3',n:'MUSIC BANK｜タイプ 03',f:'MUSICBANK③ テンプレ(2).jpg',logo:'MUSICBANK③.svg',font:'Inter',style:'mb3',x:.035,y:.72,align:'left'},
{id:'studio',n:'STUDIO K',f:'STUDIO K テンプレ(2).jpg',logo:'STUDIO K.svg',font:'Anton',style:'studio',x:.045,y:.76,align:'left'},
{id:'mnetfan',n:'M COUNTDOWN｜チッケム',f:'M COUNTDOWN チッケム テンプレ(2).jpg',logo:'M COUNTDOWN チッケム.svg',font:'Noto Sans KR',style:'mnetfan',x:.035,y:.75,align:'left'},
{id:'mnet',n:'M COUNTDOWN',f:'M COUNTDOWN テンプレ(2).jpg',logo:'M COUNTDOWN.svg',font:'Noto Sans KR',style:'mnet',x:.035,y:.75,align:'left'},
{id:'sc',n:'SHOW CHAMPION',f:'SHOW CHAMPION テンプレ(2).jpg',logo:'SHOW CHANPION.svg',font:'Inter',style:'sc',x:.035,y:.78,align:'left'},
{id:'show',n:'THE SHOW',f:'THE SHOW テンプレ(2).jpg',logo:'THE SHOW.svg',font:'Inter',style:'show',x:.045,y:.78,align:'left'}
];
let state={ti:0,photo:null,artist:'',title:'',zoom:1,ref:true,layers:[],selected:null,theme:'#ffffff'};
const fonts=['Inter','Noto Sans JP','Noto Sans KR','Poppins','DM Sans','Jost','Space Grotesk','Oswald','Roboto Condensed','Anton','Bebas Neue','Archivo Black','SUIT','Playfair Display'];
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function resetTemplate(i){state.ti=i;state.artist='';state.title='';state.photo=null;state.ref=true;buildLayers();render();}
function buildLayers(){let t=templates[state.ti];state.layers=[{id:'ref',name:'参考画像',type:'reference',visible:true,locked:true},{id:'photo',name:'写真',type:'photo',visible:true,locked:false},{id:'logo',name:'番組ロゴ',type:'logo',visible:true,locked:true},{id:'artist',name:'アーティスト名',type:'text',role:'artist',visible:true,locked:false,text:state.artist||'アーティスト名',font:t.font,size:34,weight:700,color:'#fff',x:t.x*720,y:t.y*404,stroke:true,strokeColor:'#000',sw:3,opacity:1},{id:'title',name:'タイトル',type:'text',role:'title',visible:true,locked:false,text:state.title||'タイトル',font:t.font,size:48,weight:800,color:'#fff',x:t.x*720,y:(t.y+.09)*404,stroke:true,strokeColor:'#000',sw:3,opacity:1},{id:'accent',name:'装飾・フレーム',type:'accent',visible:true,locked:true}];state.selected='title'}
function templateSrc(){return A+'templates/'+templates[state.ti].f}
async function draw(){const c=$('#canvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,720,404);let t=templates[state.ti];if(state.ref&&!state.photo){const im=await loadImg(templateSrc());ctx.drawImage(im,0,0,720,404);updateSelection();return}if(state.photo){const im=await loadImg(state.photo);cover(ctx,im,0,0,720,404)}else{ctx.fillStyle='#dfe5ee';ctx.fillRect(0,0,720,404)}await drawLogo(ctx,t);drawAccent(ctx,t);for(const l of state.layers){if(l.visible&&l.type==='text')drawText(ctx,l)}updateSelection()}
function loadImg(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src})}
function cover(ctx,im,x,y,w,h){const r=Math.max(w/im.width,h/im.height),nw=im.width*r,nh=im.height*r;ctx.drawImage(im,x+(w-nw)/2,y+(h-nh)/2,nw,nh)}
async function drawLogo(ctx,t){try{const im=await loadImg(A+'logos/'+t.logo);ctx.drawImage(im,0,0,720,404)}catch(e){}}
function drawAccent(ctx,t){ctx.save();if(['mb2','mb3'].includes(t.style)){ctx.strokeStyle='#fff';ctx.lineWidth=3;roundRect(ctx,14,10,692,384,17);ctx.stroke()}if(t.style==='mc'||t.style==='mcfan'){ctx.strokeStyle='rgba(255,255,255,.5)';ctx.lineWidth=2;ctx.strokeRect(7,8,706,388)}if(t.style==='show'){let g=ctx.createLinearGradient(0,300,0,404);g.addColorStop(0,'transparent');g.addColorStop(1,'rgba(255,255,255,.75)');ctx.fillStyle=g;ctx.fillRect(0,300,720,104)}ctx.restore()}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawText(ctx,l){ctx.save();ctx.globalAlpha=l.opacity;ctx.font=`${l.weight} ${l.size}px "${l.font}"`;ctx.textBaseline='alphabetic';ctx.textAlign='left';if(l.stroke){ctx.lineWidth=l.sw*2;ctx.strokeStyle=l.strokeColor;ctx.strokeText(l.text,l.x,l.y)}ctx.fillStyle=l.color;ctx.fillText(l.text,l.x,l.y);ctx.restore()}
function render(){const t=templates[state.ti];$('#templateName').textContent=t.n;renderLeft();renderLayers();draw();}
function renderLeft(){const p=$('#leftPanel');const t=templates[state.ti];p.innerHTML=`<div class="left-inner"><div class="eyebrow">QUICK CREATE</div><div class="section-title"><h3>かんたん作成</h3><small>3 STEP</small></div><p class="hint">テンプレートを選んだら、基本は画像・アーティスト名・タイトルだけ。ロゴや番組デザインは自動で配置されます。</p><div class="section-title"><h3>画像</h3></div><label class="drop"><input id="photo" type="file" accept="image/*"><b>＋</b><span>画像をドラッグ＆ドロップ<br>またはクリックして選択</span></label><div class="quick-input"><label>アーティスト名</label><input id="artist" value="${esc(state.artist)}" placeholder="Hearts2Hearts"></div><div class="quick-input"><label>タイトル</label><input id="title" value="${esc(state.title)}" placeholder="15-LOVE"></div><div class="section-title"><h3>テンプレート</h3><small>${templates.length}種類</small></div><div class="template-list">${templates.map((x,i)=>`<button class="template-card ${i===state.ti?'active':''}" data-ti="${i}"><img src="${A+'templates/'+x.f}"><span class="check">✓</span><div class="tc-meta"><strong>${esc(x.n)}</strong><span>${x.font}</span></div></button>`).join('')}</div></div>`;$('#photo').onchange=e=>loadPhoto(e.target.files[0]);['artist','title'].forEach(id=>$('#'+id).oninput=e=>{state[id]=e.target.value;let l=state.layers.find(x=>x.id===id);if(l)l.text=state[id];renderLayers();draw()});$$('[data-ti]').forEach(b=>b.onclick=()=>resetTemplate(+b.dataset.ti));}
function loadPhoto(file){if(!file)return;let r=new FileReader();r.onload=e=>{state.photo=e.target.result;state.ref=false;draw();};r.readAsDataURL(file)}
function renderLayers(){const p=$('#layers');p.innerHTML=state.layers.slice().reverse().map(l=>`<div class="layer ${l.id===state.selected?'active':''}" data-layer="${l.id}"><span class="drag">⋮⋮</span><button class="eye">${l.visible?'◉':'○'}</button><span class="name">${esc(l.name)}</span><button class="lock">${l.locked?'●':'○'}</button></div>`).join('');$$('[data-layer]').forEach(e=>e.onclick=()=>{state.selected=e.dataset.layer;renderLayers();renderProperties()});renderProperties()}
function renderProperties(){const p=$('#properties'),l=state.layers.find(x=>x.id===state.selected);if(!l){p.innerHTML='';return}if(l.type==='text'){p.innerHTML=`<div class="prop-title">${esc(l.name)}</div><div class="field"><label>文字</label><input id="pt" value="${esc(l.text)}"></div><div class="field"><label>フォント</label><select id="pf">${fonts.map(f=>`<option ${f===l.font?'selected':''}>${f}</option>`).join('')}</select></div><div class="two"><div class="field"><label>サイズ</label><input id="ps" type="number" value="${l.size}"></div><div class="field"><label>太さ</label><input id="pw" type="number" value="${l.weight}"></div></div><div class="two"><div class="field"><label>X</label><input id="px" type="number" value="${Math.round(l.x)}"></div><div class="field"><label>Y</label><input id="py" type="number" value="${Math.round(l.y)}"></div></div><div class="field"><label>文字色</label><input id="pc" type="color" value="${l.color}"></div><div class="field"><label>縁取り</label><div class="two"><input id="psc" type="color" value="${l.strokeColor}"><input id="psw" type="number" value="${l.sw}"></div></div>`;['pt','pf','ps','pw','px','py','pc','psc','psw'].forEach(id=>$('#'+id).oninput=e=>{let k={pt:'text',pf:'font',ps:'size',pw:'weight',px:'x',py:'y',pc:'color',psc:'strokeColor',psw:'sw'}[id];l[k]=['size','weight','x','y','sw'].includes(k)?+e.target.value:e.target.value;if(l.role==='artist')state.artist=l.text;if(l.role==='title')state.title=l.text;draw();});}else{p.innerHTML=`<div class="prop-title">${esc(l.name)}</div><p class="hint">このレイヤーはテンプレートの構成要素です。表示・非表示は右のレイヤー一覧から変更できます。</p>`}}
let dragInfo=null;
$('#stage').addEventListener('pointerdown',e=>{if(e.target!==$('#canvas'))return;const r=$('#stage').getBoundingClientRect();const x=(e.clientX-r.left)/state.zoom,y=(e.clientY-r.top)/state.zoom;let hit=null;for(let i=state.layers.length-1;i>=0;i--){const l=state.layers[i];if(l.type==='text'&&l.visible&&!l.locked&&x>=l.x-8&&x<=l.x+330&&y>=l.y-l.size&&y<=l.y+8){hit=l;break}}if(!hit)return;state.selected=hit.id;dragInfo={l:hit,ox:x-hit.x,oy:y-hit.y};renderLayers();$('#stage').setPointerCapture(e.pointerId)});
$('#stage').addEventListener('pointermove',e=>{if(!dragInfo)return;const r=$('#stage').getBoundingClientRect();const x=(e.clientX-r.left)/state.zoom,y=(e.clientY-r.top)/state.zoom;dragInfo.l.x=Math.round(x-dragInfo.ox);dragInfo.l.y=Math.round(y-dragInfo.oy);draw();renderProperties()});
$('#stage').addEventListener('pointerup',()=>dragInfo=null);$('#stage').addEventListener('pointercancel',()=>dragInfo=null);
function setupTabs(){$$('.tab').forEach(b=>b.onclick=()=>{if(b.dataset.tab==='templates')renderLeft();else if(b.dataset.tab==='photo')renderPhotoPanel();else renderAdvanced();$$('.tab').forEach(x=>x.classList.toggle('active',x===b))})}
function renderPhotoPanel(){const p=$('#leftPanel');p.innerHTML=`<div class="left-inner"><div class="eyebrow">PHOTO</div><div class="section-title"><h3>画像</h3></div><label class="drop"><input id="photo2" type="file" accept="image/*"><b>＋</b><span>画像を差し替える</span></label><div class="section-title"><h3>配置</h3></div><button class="toggle active" id="center">中央配置</button><p class="hint">写真は720×404の比率に合わせて中央からトリミングされます。</p></div>`;$('#photo2').onchange=e=>loadPhoto(e.target.files[0]);$('#center').onclick=()=>draw()}
function renderAdvanced(){const p=$('#leftPanel');p.innerHTML=`<div class="left-inner"><div class="eyebrow">ADVANCED</div><div class="section-title"><h3>詳細編集</h3></div><p class="hint">Photoshop / Canvaのように、右のレイヤーを選択して位置・フォント・色・サイズを細かく調整できます。</p><div class="section-title"><h3>テーマカラー</h3></div><div class="swatches">${['#ffffff','#000000','#a7d9ff','#cdb9ff','#ffb5d2','#c5f0df','#ffe2a8','#7b74ee'].map(c=>`<button class="swatch" style="background:${c}" data-c="${c}"></button>`).join('')}</div></div>`;$$('[data-c]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.c;draw()})}
function updateSelection(){const l=state.layers.find(x=>x.id===state.selected);const s=$('#selection');if(!l||l.type!=='text'||!l.visible){s.style.display='none';return}s.style.display='block';s.style.left=(l.x-4)+'px';s.style.top=(l.y-l.size-4)+'px';s.style.width='220px';s.style.height=(l.size+10)+'px'}
$('#addText').onclick=()=>{let n={id:'text'+Date.now(),name:'追加テキスト',type:'text',text:'テキストを入力',font:'Inter',size:36,weight:700,color:'#fff',x:300,y:200,stroke:true,strokeColor:'#000',sw:2,opacity:1,visible:true,locked:false};state.layers.push(n);state.selected=n.id;renderLayers();draw()};
$('#refToggle').onclick=()=>{state.ref=!state.ref;draw()};$('#fit').onclick=()=>{let l=state.layers.find(x=>x.id==='photo');if(l){}};$('#zoomIn').onclick=()=>{state.zoom=Math.min(1.6,state.zoom+.1);applyZoom()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(.6,state.zoom-.1);applyZoom()};function applyZoom(){$('#zoom').textContent=Math.round(state.zoom*100)+'%';$('#stage').style.transform=`scale(${state.zoom})`}
$('#export').onclick=()=>$('#exportModal').classList.remove('hidden');$('#quality').oninput=e=>$('#qualityVal').textContent=e.target.value;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));$('#download').onclick=()=>exportImage();
function exportImage(){const c=$('#canvas'),scale=+$('#scale').value,fmt=$('#format').value,q=+$('#quality').value/100;const out=document.createElement('canvas');out.width=c.width*scale;out.height=c.height*scale;const x=out.getContext('2d');x.scale(scale,scale);x.drawImage(c,0,0);const mime=fmt==='jpeg'?'image/jpeg':fmt==='webp'?'image/webp':'image/png';const a=document.createElement('a');a.download=`thumbly-${Date.now()}.${fmt==='jpeg'?'jpg':fmt}`;a.href=out.toDataURL(mime,q);a.click();saveHistory(a.href)}
function saveHistory(src){let h=JSON.parse(localStorage.getItem('thumblyHistory')||'[]');h.unshift({src,name:templates[state.ti].n,title:state.title,artist:state.artist,date:new Date().toLocaleString('ja-JP')});h=h.slice(0,20);localStorage.setItem('thumblyHistory',JSON.stringify(h))}
$('#history').onclick=()=>{let h=JSON.parse(localStorage.getItem('thumblyHistory')||'[]');$('#historyGrid').innerHTML=h.length?h.map(x=>`<div class="history-item"><img src="${x.src}"><div><b>${esc(x.name)}</b><br>${esc(x.artist)}<br>${esc(x.title)}<br><small>${esc(x.date)}</small></div></div>`).join(''):'まだ作成履歴がありません。';$('#historyModal').classList.remove('hidden')};$('#new').onclick=()=>resetTemplate(0);
setupTabs();buildLayers();render();
