const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const A='assets/';
const templates=[
{id:'scfan',n:'SHOW CHAMPION｜チッケム',f:'SHOW CHANPION チッケム テンプレ(2).jpg',logo:'SHOW CHANPION チッケム.svg',style:'scfan',font:'Noto Sans KR',p1:[24,286,26,700],p2:[24,352,52,800],labels:['アーティスト名','メンバー名']},
{id:'inkfan',n:'人気歌謡｜チッケム',f:'人気歌謡 チッケム テンプレ(2).jpg',logo:'人気歌謡 チッケム.svg',style:'inkfan',font:'Noto Sans KR',p1:[24,346,52,800],p2:[24,379,27,400],labels:['メンバー名','グループ名']},
{id:'ink',n:'人気歌謡',f:'人気歌謡 テンプレ(2).jpg',logo:'人気歌謡.svg',style:'ink',font:'Inter',p1:[25,348,40,700],p2:[25,380,27,400],labels:['アーティスト名','タイトル']},
{id:'mcfan',n:'音楽中心｜チッケム',f:'音楽中心 チッケム テンプレ(2).jpg',logo:'音楽中心 チッケム(1).svg',style:'mcfan',font:'Noto Sans KR',p1:[39,140,25,700],p2:[39,354,54,800],labels:['アーティスト名','メンバー名']},
{id:'mc',n:'音楽中心',f:'音楽中心 テンプレ(2).jpg',logo:'音楽中心(1).svg',style:'mc',font:'Noto Sans KR',p1:[37,286,48,800],p2:[37,352,28,700],labels:['アーティスト名','タイトル']},
{id:'mb1',n:'MUSIC BANK｜タイプ 01',f:'MUSICBANK① テンプレ(2).jpg',logo:'MUSICBANK①.svg',style:'mb1',font:'Inter',p1:[24,264,43,700],p2:[24,318,30,500],labels:['アーティスト名','タイトル']},
{id:'mb2',n:'MUSIC BANK｜タイプ 02',f:'MUSICBANK② テンプレ(2).jpg',logo:'MUSICBANK②.svg',style:'mb2',font:'Inter',p1:[25,340,50,800],p2:[25,377,30,500],labels:['アーティスト名','タイトル']},
{id:'mb3',n:'MUSIC BANK｜タイプ 03',f:'MUSICBANK③ テンプレ(2).jpg',logo:'MUSICBANK③.svg',style:'mb3',font:'Inter',p1:[24,286,43,700],p2:[24,324,30,500],labels:['アーティスト名','タイトル']},
{id:'studio',n:'STUDIO K',f:'STUDIO K テンプレ(2).jpg',logo:'STUDIO K.svg',style:'studio',font:'Anton',p1:[33,350,40,800],p2:[33,382,27,700],labels:['アーティスト名','タイトル']},
{id:'mnetfan',n:'M COUNTDOWN｜チッケム',f:'M COUNTDOWN チッケム テンプレ(2).jpg',logo:'M COUNTDOWN チッケム.svg',style:'mnetfan',font:'Noto Sans KR',p1:[25,345,28,500],p2:[25,383,50,800],labels:['アーティスト名','メンバー名']},
{id:'mnet',n:'M COUNTDOWN',f:'M COUNTDOWN テンプレ(2).jpg',logo:'M COUNTDOWN.svg',style:'mnet',font:'Noto Sans KR',p1:[24,352,48,800],p2:[24,384,28,600],labels:['アーティスト名','タイトル']},
{id:'sc',n:'SHOW CHAMPION',f:'SHOW CHAMPION テンプレ(2).jpg',logo:'SHOW CHANPION.svg',style:'sc',font:'Inter',p1:[25,346,48,800],p2:[25,383,30,500],labels:['アーティスト名','タイトル']},
{id:'show',n:'THE SHOW',f:'THE SHOW テンプレ(2).jpg',logo:'THE SHOW.svg',style:'show',font:'Inter',p1:[33,356,46,800],p2:[33,389,27,500],labels:['アーティスト名','タイトル']}
];
let state={ti:0,photo:null,artist:'',title:'',zoom:1,ref:true,layers:[],selected:null,theme:'#ffffff'};
const fonts=['Inter','Noto Sans JP','Noto Sans KR','Poppins','DM Sans','Jost','Space Grotesk','Oswald','Roboto Condensed','Anton','Bebas Neue','Archivo Black','SUIT','Playfair Display'];
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function resetTemplate(i){state.ti=i;state.artist='';state.title='';state.photo=null;state.ref=true;buildLayers();render()}
function posObj(id,role,text){const t=templates[state.ti],p=role==='artist'?t.p1:t.p2;return{id,name:t.labels[role==='artist'?0:1],type:'text',role,visible:true,locked:false,text:text||'',font:t.font,size:p[2],weight:p[3],color:'#fff',x:p[0],y:p[1],stroke:true,strokeColor:'#000',sw:role==='artist'?2.5:3,opacity:1}}
function buildLayers(){const t=templates[state.ti];state.layers=[{id:'photo',name:'写真',type:'photo',visible:true,locked:false},{id:'logo',name:'番組ロゴ',type:'logo',visible:true,locked:true},posObj('artist','artist',state.artist||''),posObj('title','title',state.title||''),{id:'accent',name:'枠・装飾',type:'accent',visible:true,locked:true}];state.selected='artist'}
function templateSrc(){return A+'templates/'+templates[state.ti].f}
function loadImg(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src})}
function cover(ctx,im,x,y,w,h){const r=Math.max(w/im.width,h/im.height),nw=im.width*r,nh=im.height*r;ctx.drawImage(im,x+(w-nw)/2,y+(h-nh)/2,nw,nh)}
async function draw(){const c=$('#canvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,720,404);const t=templates[state.ti];if(state.photo){const im=await loadImg(state.photo);cover(ctx,im,0,0,720,404)}else if(state.ref){const im=await loadImg(templateSrc());ctx.drawImage(im,0,0,720,404);updateSelection();return}else{ctx.fillStyle='#dfe5ee';ctx.fillRect(0,0,720,404)}if(state.layers.find(x=>x.id==='logo')?.visible)await drawLogo(ctx,t);drawAccent(ctx,t);for(const l of state.layers){if(l.visible&&l.type==='text'&&l.text)drawText(ctx,l)}updateSelection()}
async function drawLogo(ctx,t){try{const im=await loadImg(A+'logos/'+t.logo);ctx.drawImage(im,0,0,720,404)}catch(e){}}
function drawAccent(ctx,t){ctx.save();if(['mb2','mb3'].includes(t.style)){ctx.strokeStyle='#fff';ctx.lineWidth=3;roundRect(ctx,14,10,692,384,17);ctx.stroke()}if(['mc','mcfan'].includes(t.style)){ctx.strokeStyle='rgba(255,255,255,.5)';ctx.lineWidth=2;ctx.strokeRect(7,8,706,388)}if(t.style==='show'){let g=ctx.createLinearGradient(0,300,0,404);g.addColorStop(0,'transparent');g.addColorStop(1,'rgba(255,255,255,.75)');ctx.fillStyle=g;ctx.fillRect(0,300,720,104)}ctx.restore()}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawText(ctx,l){ctx.save();ctx.globalAlpha=l.opacity;ctx.font=`${l.weight} ${l.size}px "${l.font}"`;ctx.textBaseline='alphabetic';ctx.textAlign='left';if(l.stroke){ctx.lineWidth=l.sw*2;ctx.strokeStyle=l.strokeColor;ctx.strokeText(l.text,l.x,l.y)}ctx.fillStyle=l.color;ctx.fillText(l.text,l.x,l.y);ctx.restore()}
function render(){const t=templates[state.ti];$('#templateName').textContent=t.n;renderLeft();renderLayers();draw()}
function renderLeft(){const p=$('#leftPanel'),t=templates[state.ti];p.innerHTML=`<div class="left-inner quick"><div class="eyebrow">QUICK CREATE</div><div class="quick-title"><h3>かんたん作成</h3><span>STEP 1 / 2 / 3</span></div><div class="step"><b>1</b><label>テンプレート</label><div class="selected-template">${esc(t.n)}</div></div><div class="step"><b>2</b><label>${esc(t.labels[0])}</label><input id="artist" value="${esc(state.artist)}" placeholder="入力してください"></div><div class="step"><b>3</b><label>${esc(t.labels[1])}</label><input id="title" value="${esc(state.title)}" placeholder="入力してください"></div><div class="step"><b>4</b><label>画像</label><label class="drop"><input id="photo" type="file" accept="image/*"><span>${state.photo?'画像を変更する':'写真を追加する'}</span></label></div><button class="mobile-done" id="done">この内容で完成</button><div class="section-title"><h3>テンプレートを変更</h3><small>${templates.length}種類</small></div><div class="template-list">${templates.map((x,i)=>`<button class="template-card ${i===state.ti?'active':''}" data-ti="${i}"><img src="${A+'templates/'+x.f}"><span class="check">✓</span><div class="tc-meta"><strong>${esc(x.n)}</strong><span>${esc(x.labels.join(' / '))}</span></div></button>`).join('')}</div></div>`;$('#photo').onchange=e=>loadPhoto(e.target.files[0]);$('#artist').oninput=e=>{state.artist=e.target.value;let l=state.layers.find(x=>x.id==='artist');if(l)l.text=state.artist;draw()};$('#title').oninput=e=>{state.title=e.target.value;let l=state.layers.find(x=>x.id==='title');if(l)l.text=state.title;draw()};$('#done').onclick=()=>{$('#export').click()};$$('[data-ti]').forEach(b=>b.onclick=()=>resetTemplate(+b.dataset.ti))}
function loadPhoto(file){if(!file)return;const r=new FileReader();r.onload=e=>{state.photo=e.target.result;state.ref=false;draw();renderLeft()};r.readAsDataURL(file)}
function renderLayers(){const p=$('#layers');p.innerHTML=state.layers.slice().reverse().map(l=>`<div class="layer ${l.id===state.selected?'active':''}" data-layer="${l.id}"><span class="drag">⋮⋮</span><button class="eye">${l.visible?'◉':'○'}</button><span class="name">${esc(l.name)}</span><button class="lock">${l.locked?'●':'○'}</button></div>`).join('');$$('[data-layer]').forEach(e=>e.onclick=()=>{state.selected=e.dataset.layer;renderLayers();renderProperties()});renderProperties()}
function renderProperties(){const p=$('#properties'),l=state.layers.find(x=>x.id===state.selected);if(!l){p.innerHTML='';return}if(l.type==='text'){p.innerHTML=`<div class="prop-title">${esc(l.name)}</div><div class="field"><label>文字</label><input id="pt" value="${esc(l.text)}"></div><div class="field"><label>フォント</label><select id="pf">${fonts.map(f=>`<option ${f===l.font?'selected':''}>${f}</option>`).join('')}</select></div><div class="two"><div class="field"><label>サイズ</label><input id="ps" type="number" value="${l.size}"></div><div class="field"><label>太さ</label><input id="pw" type="number" value="${l.weight}"></div></div><div class="two"><div class="field"><label>X</label><input id="px" type="number" value="${Math.round(l.x)}"></div><div class="field"><label>Y</label><input id="py" type="number" value="${Math.round(l.y)}"></div></div><div class="field"><label>文字色</label><input id="pc" type="color" value="${l.color}"></div>`;['pt','pf','ps','pw','px','py','pc'].forEach(id=>$('#'+id).oninput=e=>{const k={pt:'text',pf:'font',ps:'size',pw:'weight',px:'x',py:'y',pc:'color'}[id];l[k]=['size','weight','x','y'].includes(k)?+e.target.value:e.target.value;if(l.role==='artist')state.artist=l.text;if(l.role==='title')state.title=l.text;draw();renderLeft()})}else p.innerHTML=`<div class="prop-title">${esc(l.name)}</div><p class="hint">テンプレートに合わせて自動配置されています。</p>`}
function setupTabs(){$$('.tab').forEach(b=>b.onclick=()=>{if(b.dataset.tab==='templates')renderLeft();else if(b.dataset.tab==='photo')renderPhotoPanel();else renderAdvanced();$$('.tab').forEach(x=>x.classList.toggle('active',x===b))})}
function renderPhotoPanel(){const p=$('#leftPanel');p.innerHTML=`<div class="left-inner"><div class="eyebrow">PHOTO</div><div class="section-title"><h3>画像</h3></div><label class="drop"><input id="photo2" type="file" accept="image/*"><b>＋</b><span>画像を差し替える</span></label><p class="hint">写真は自動で16:9に合わせます。</p></div>`;$('#photo2').onchange=e=>loadPhoto(e.target.files[0])}
function renderAdvanced(){const p=$('#leftPanel');p.innerHTML=`<div class="left-inner"><div class="eyebrow">ADVANCED</div><div class="section-title"><h3>詳細編集</h3></div><p class="hint">スマホでは基本操作だけで作成できます。位置やフォントを細かく変えたい場合だけ使用してください。</p><div class="section-title"><h3>テーマカラー</h3></div><div class="swatches">${['#ffffff','#000000','#a7d9ff','#cdb9ff','#ffb5d2','#c5f0df','#ffe2a8','#7b74ee'].map(c=>`<button class="swatch" style="background:${c}" data-c="${c}"></button>`).join('')}</div></div>`;$$('[data-c]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.c;draw()})}
function updateSelection(){const l=state.layers.find(x=>x.id===state.selected),s=$('#selection');if(!l||l.type!=='text'||!l.visible||!l.text){s.style.display='none';return}s.style.display='block';s.style.left=(l.x-4)+'px';s.style.top=(l.y-l.size-4)+'px';s.style.width=Math.max(80,l.text.length*l.size*.58+12)+'px';s.style.height=(l.size+10)+'px'}
$('#addText').onclick=()=>{let n={id:'text'+Date.now(),name:'追加テキスト',type:'text',text:'テキストを入力',font:'Inter',size:36,weight:700,color:'#fff',x:300,y:200,stroke:true,strokeColor:'#000',sw:2,opacity:1,visible:true,locked:false};state.layers.push(n);state.selected=n.id;renderLayers();draw()};
$('#refToggle').onclick=()=>{state.ref=!state.ref;draw()};
$('#fit').onclick=()=>{state.photo&&draw()};
$('#zoomIn').onclick=()=>{state.zoom=Math.min(1.6,state.zoom+.1);applyZoom()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(.6,state.zoom-.1);applyZoom()};function applyZoom(){$('#zoom').textContent=Math.round(state.zoom*100)+'%';$('#stage').style.transform=`scale(${state.zoom})`}
setupTabs();buildLayers();render();
$('#export').onclick=()=>$('#exportModal').classList.remove('hidden');$('#quality').oninput=e=>$('#qualityVal').textContent=e.target.value;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));$('#download').onclick=()=>exportImage();
function exportImage(){const c=$('#canvas'),scale=+$('#scale').value,fmt=$('#format').value,q=+$('#quality').value/100;const out=document.createElement('canvas');out.width=c.width*scale;out.height=c.height*scale;const x=out.getContext('2d');x.scale(scale,scale);x.drawImage(c,0,0);const mime=fmt==='jpeg'?'image/jpeg':fmt==='webp'?'image/webp':'image/png';const a=document.createElement('a');a.download=`thumbly-${Date.now()}.${fmt==='jpeg'?'jpg':fmt}`;a.href=out.toDataURL(mime,q);a.click();saveHistory(a.href)}
function saveHistory(src){let h=JSON.parse(localStorage.getItem('thumblyHistory')||'[]');h.unshift({src,name:templates[state.ti].n,title:state.title,artist:state.artist,date:new Date().toLocaleString('ja-JP')});h=h.slice(0,20);localStorage.setItem('thumblyHistory',JSON.stringify(h))}
$('#history').onclick=()=>{let h=JSON.parse(localStorage.getItem('thumblyHistory')||'[]');$('#historyGrid').innerHTML=h.length?h.map(x=>`<div class="history-item"><img src="${x.src}"><div><b>${esc(x.name)}</b><br>${esc(x.artist)}<br>${esc(x.title)}<br><small>${esc(x.date)}</small></div></div>`).join(''):'まだ作成履歴がありません。';$('#historyModal').classList.remove('hidden')};$('#new').onclick=()=>resetTemplate(0);
setupTabs();buildLayers();render();
